// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class Courses extends Table with TableInfo<Courses, CoursesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Courses(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    hasAutoIncrement: true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
  );
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> gameTitle = GeneratedColumn<String>(
    'game_title',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [id, name, gameTitle];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'courses';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {name, gameTitle},
  ];
  @override
  CoursesData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return CoursesData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}id'],
      )!,
      name: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}name'],
      )!,
      gameTitle: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}game_title'],
      )!,
    );
  }

  @override
  Courses createAlias(String alias) {
    return Courses(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['UNIQUE(name, game_title)'];
  @override
  bool get dontWriteConstraints => true;
}

class CoursesData extends DataClass implements Insertable<CoursesData> {
  final int id;
  final String name;
  final String gameTitle;
  const CoursesData({
    required this.id,
    required this.name,
    required this.gameTitle,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['name'] = Variable<String>(name);
    map['game_title'] = Variable<String>(gameTitle);
    return map;
  }

  CoursesCompanion toCompanion(bool nullToAbsent) {
    return CoursesCompanion(
      id: Value(id),
      name: Value(name),
      gameTitle: Value(gameTitle),
    );
  }

  factory CoursesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return CoursesData(
      id: serializer.fromJson<int>(json['id']),
      name: serializer.fromJson<String>(json['name']),
      gameTitle: serializer.fromJson<String>(json['gameTitle']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'name': serializer.toJson<String>(name),
      'gameTitle': serializer.toJson<String>(gameTitle),
    };
  }

  CoursesData copyWith({int? id, String? name, String? gameTitle}) =>
      CoursesData(
        id: id ?? this.id,
        name: name ?? this.name,
        gameTitle: gameTitle ?? this.gameTitle,
      );
  CoursesData copyWithCompanion(CoursesCompanion data) {
    return CoursesData(
      id: data.id.present ? data.id.value : this.id,
      name: data.name.present ? data.name.value : this.name,
      gameTitle: data.gameTitle.present ? data.gameTitle.value : this.gameTitle,
    );
  }

  @override
  String toString() {
    return (StringBuffer('CoursesData(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('gameTitle: $gameTitle')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, name, gameTitle);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is CoursesData &&
          other.id == this.id &&
          other.name == this.name &&
          other.gameTitle == this.gameTitle);
}

class CoursesCompanion extends UpdateCompanion<CoursesData> {
  final Value<int> id;
  final Value<String> name;
  final Value<String> gameTitle;
  const CoursesCompanion({
    this.id = const Value.absent(),
    this.name = const Value.absent(),
    this.gameTitle = const Value.absent(),
  });
  CoursesCompanion.insert({
    this.id = const Value.absent(),
    required String name,
    required String gameTitle,
  }) : name = Value(name),
       gameTitle = Value(gameTitle);
  static Insertable<CoursesData> custom({
    Expression<int>? id,
    Expression<String>? name,
    Expression<String>? gameTitle,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (gameTitle != null) 'game_title': gameTitle,
    });
  }

  CoursesCompanion copyWith({
    Value<int>? id,
    Value<String>? name,
    Value<String>? gameTitle,
  }) {
    return CoursesCompanion(
      id: id ?? this.id,
      name: name ?? this.name,
      gameTitle: gameTitle ?? this.gameTitle,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (name.present) {
      map['name'] = Variable<String>(name.value);
    }
    if (gameTitle.present) {
      map['game_title'] = Variable<String>(gameTitle.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('CoursesCompanion(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('gameTitle: $gameTitle')
          ..write(')'))
        .toString();
  }
}

class CourseSets extends Table with TableInfo<CourseSets, CourseSetsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  CourseSets(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    hasAutoIncrement: true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
  );
  late final GeneratedColumn<int> courseId = GeneratedColumn<int>(
    'course_id',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES courses(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [id, courseId, name];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'course_sets';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {courseId, name},
  ];
  @override
  CourseSetsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return CourseSetsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}id'],
      )!,
      courseId: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}course_id'],
      )!,
      name: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}name'],
      )!,
    );
  }

  @override
  CourseSets createAlias(String alias) {
    return CourseSets(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['UNIQUE(course_id, name)'];
  @override
  bool get dontWriteConstraints => true;
}

class CourseSetsData extends DataClass implements Insertable<CourseSetsData> {
  final int id;
  final int courseId;
  final String name;
  const CourseSetsData({
    required this.id,
    required this.courseId,
    required this.name,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['course_id'] = Variable<int>(courseId);
    map['name'] = Variable<String>(name);
    return map;
  }

  CourseSetsCompanion toCompanion(bool nullToAbsent) {
    return CourseSetsCompanion(
      id: Value(id),
      courseId: Value(courseId),
      name: Value(name),
    );
  }

  factory CourseSetsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return CourseSetsData(
      id: serializer.fromJson<int>(json['id']),
      courseId: serializer.fromJson<int>(json['courseId']),
      name: serializer.fromJson<String>(json['name']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'courseId': serializer.toJson<int>(courseId),
      'name': serializer.toJson<String>(name),
    };
  }

  CourseSetsData copyWith({int? id, int? courseId, String? name}) =>
      CourseSetsData(
        id: id ?? this.id,
        courseId: courseId ?? this.courseId,
        name: name ?? this.name,
      );
  CourseSetsData copyWithCompanion(CourseSetsCompanion data) {
    return CourseSetsData(
      id: data.id.present ? data.id.value : this.id,
      courseId: data.courseId.present ? data.courseId.value : this.courseId,
      name: data.name.present ? data.name.value : this.name,
    );
  }

  @override
  String toString() {
    return (StringBuffer('CourseSetsData(')
          ..write('id: $id, ')
          ..write('courseId: $courseId, ')
          ..write('name: $name')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, courseId, name);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is CourseSetsData &&
          other.id == this.id &&
          other.courseId == this.courseId &&
          other.name == this.name);
}

class CourseSetsCompanion extends UpdateCompanion<CourseSetsData> {
  final Value<int> id;
  final Value<int> courseId;
  final Value<String> name;
  const CourseSetsCompanion({
    this.id = const Value.absent(),
    this.courseId = const Value.absent(),
    this.name = const Value.absent(),
  });
  CourseSetsCompanion.insert({
    this.id = const Value.absent(),
    required int courseId,
    required String name,
  }) : courseId = Value(courseId),
       name = Value(name);
  static Insertable<CourseSetsData> custom({
    Expression<int>? id,
    Expression<int>? courseId,
    Expression<String>? name,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (courseId != null) 'course_id': courseId,
      if (name != null) 'name': name,
    });
  }

  CourseSetsCompanion copyWith({
    Value<int>? id,
    Value<int>? courseId,
    Value<String>? name,
  }) {
    return CourseSetsCompanion(
      id: id ?? this.id,
      courseId: courseId ?? this.courseId,
      name: name ?? this.name,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (courseId.present) {
      map['course_id'] = Variable<int>(courseId.value);
    }
    if (name.present) {
      map['name'] = Variable<String>(name.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('CourseSetsCompanion(')
          ..write('id: $id, ')
          ..write('courseId: $courseId, ')
          ..write('name: $name')
          ..write(')'))
        .toString();
  }
}

class Events extends Table with TableInfo<Events, EventsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Events(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    hasAutoIncrement: true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
  );
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> season = GeneratedColumn<int>(
    'season',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 1',
    defaultValue: const CustomExpression('1'),
  );
  late final GeneratedColumn<int> finishPosition = GeneratedColumn<int>(
    'finish_position',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> tied = GeneratedColumn<int>(
    'tied',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0 CHECK (tied IN (0, 1))',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<int> missedCut = GeneratedColumn<int>(
    'missed_cut',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0 CHECK (missed_cut IN (0, 1))',
    defaultValue: const CustomExpression('0'),
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    name,
    season,
    finishPosition,
    tied,
    missedCut,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'events';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {name, season},
  ];
  @override
  EventsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return EventsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}id'],
      )!,
      name: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}name'],
      )!,
      season: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}season'],
      )!,
      finishPosition: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}finish_position'],
      ),
      tied: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}tied'],
      )!,
      missedCut: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}missed_cut'],
      )!,
    );
  }

  @override
  Events createAlias(String alias) {
    return Events(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['UNIQUE(name, season)'];
  @override
  bool get dontWriteConstraints => true;
}

class EventsData extends DataClass implements Insertable<EventsData> {
  final int id;
  final String name;
  final int season;
  final int? finishPosition;
  final int tied;
  final int missedCut;
  const EventsData({
    required this.id,
    required this.name,
    required this.season,
    this.finishPosition,
    required this.tied,
    required this.missedCut,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['name'] = Variable<String>(name);
    map['season'] = Variable<int>(season);
    if (!nullToAbsent || finishPosition != null) {
      map['finish_position'] = Variable<int>(finishPosition);
    }
    map['tied'] = Variable<int>(tied);
    map['missed_cut'] = Variable<int>(missedCut);
    return map;
  }

  EventsCompanion toCompanion(bool nullToAbsent) {
    return EventsCompanion(
      id: Value(id),
      name: Value(name),
      season: Value(season),
      finishPosition: finishPosition == null && nullToAbsent
          ? const Value.absent()
          : Value(finishPosition),
      tied: Value(tied),
      missedCut: Value(missedCut),
    );
  }

  factory EventsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return EventsData(
      id: serializer.fromJson<int>(json['id']),
      name: serializer.fromJson<String>(json['name']),
      season: serializer.fromJson<int>(json['season']),
      finishPosition: serializer.fromJson<int?>(json['finishPosition']),
      tied: serializer.fromJson<int>(json['tied']),
      missedCut: serializer.fromJson<int>(json['missedCut']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'name': serializer.toJson<String>(name),
      'season': serializer.toJson<int>(season),
      'finishPosition': serializer.toJson<int?>(finishPosition),
      'tied': serializer.toJson<int>(tied),
      'missedCut': serializer.toJson<int>(missedCut),
    };
  }

  EventsData copyWith({
    int? id,
    String? name,
    int? season,
    Value<int?> finishPosition = const Value.absent(),
    int? tied,
    int? missedCut,
  }) => EventsData(
    id: id ?? this.id,
    name: name ?? this.name,
    season: season ?? this.season,
    finishPosition: finishPosition.present
        ? finishPosition.value
        : this.finishPosition,
    tied: tied ?? this.tied,
    missedCut: missedCut ?? this.missedCut,
  );
  EventsData copyWithCompanion(EventsCompanion data) {
    return EventsData(
      id: data.id.present ? data.id.value : this.id,
      name: data.name.present ? data.name.value : this.name,
      season: data.season.present ? data.season.value : this.season,
      finishPosition: data.finishPosition.present
          ? data.finishPosition.value
          : this.finishPosition,
      tied: data.tied.present ? data.tied.value : this.tied,
      missedCut: data.missedCut.present ? data.missedCut.value : this.missedCut,
    );
  }

  @override
  String toString() {
    return (StringBuffer('EventsData(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('season: $season, ')
          ..write('finishPosition: $finishPosition, ')
          ..write('tied: $tied, ')
          ..write('missedCut: $missedCut')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode =>
      Object.hash(id, name, season, finishPosition, tied, missedCut);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is EventsData &&
          other.id == this.id &&
          other.name == this.name &&
          other.season == this.season &&
          other.finishPosition == this.finishPosition &&
          other.tied == this.tied &&
          other.missedCut == this.missedCut);
}

class EventsCompanion extends UpdateCompanion<EventsData> {
  final Value<int> id;
  final Value<String> name;
  final Value<int> season;
  final Value<int?> finishPosition;
  final Value<int> tied;
  final Value<int> missedCut;
  const EventsCompanion({
    this.id = const Value.absent(),
    this.name = const Value.absent(),
    this.season = const Value.absent(),
    this.finishPosition = const Value.absent(),
    this.tied = const Value.absent(),
    this.missedCut = const Value.absent(),
  });
  EventsCompanion.insert({
    this.id = const Value.absent(),
    required String name,
    this.season = const Value.absent(),
    this.finishPosition = const Value.absent(),
    this.tied = const Value.absent(),
    this.missedCut = const Value.absent(),
  }) : name = Value(name);
  static Insertable<EventsData> custom({
    Expression<int>? id,
    Expression<String>? name,
    Expression<int>? season,
    Expression<int>? finishPosition,
    Expression<int>? tied,
    Expression<int>? missedCut,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (season != null) 'season': season,
      if (finishPosition != null) 'finish_position': finishPosition,
      if (tied != null) 'tied': tied,
      if (missedCut != null) 'missed_cut': missedCut,
    });
  }

  EventsCompanion copyWith({
    Value<int>? id,
    Value<String>? name,
    Value<int>? season,
    Value<int?>? finishPosition,
    Value<int>? tied,
    Value<int>? missedCut,
  }) {
    return EventsCompanion(
      id: id ?? this.id,
      name: name ?? this.name,
      season: season ?? this.season,
      finishPosition: finishPosition ?? this.finishPosition,
      tied: tied ?? this.tied,
      missedCut: missedCut ?? this.missedCut,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (name.present) {
      map['name'] = Variable<String>(name.value);
    }
    if (season.present) {
      map['season'] = Variable<int>(season.value);
    }
    if (finishPosition.present) {
      map['finish_position'] = Variable<int>(finishPosition.value);
    }
    if (tied.present) {
      map['tied'] = Variable<int>(tied.value);
    }
    if (missedCut.present) {
      map['missed_cut'] = Variable<int>(missedCut.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('EventsCompanion(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('season: $season, ')
          ..write('finishPosition: $finishPosition, ')
          ..write('tied: $tied, ')
          ..write('missedCut: $missedCut')
          ..write(')'))
        .toString();
  }
}

class Rounds extends Table with TableInfo<Rounds, RoundsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Rounds(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    hasAutoIncrement: true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
  );
  late final GeneratedColumn<String> date = GeneratedColumn<String>(
    'date',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> courseId = GeneratedColumn<int>(
    'course_id',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES courses(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<int> roundNumber = GeneratedColumn<int>(
    'round_number',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 1',
    defaultValue: const CustomExpression('1'),
  );
  late final GeneratedColumn<String> teeSet = GeneratedColumn<String>(
    'tee_set',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> courseSetId = GeneratedColumn<int>(
    'course_set_id',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL REFERENCES course_sets(id)ON DELETE SET NULL',
  );
  late final GeneratedColumn<String> weather = GeneratedColumn<String>(
    'weather',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> windSpeedMph = GeneratedColumn<int>(
    'wind_speed_mph',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> difficulty = GeneratedColumn<String>(
    'difficulty',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> notes = GeneratedColumn<String>(
    'notes',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> migrationCanary = GeneratedColumn<String>(
    'migration_canary',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> eventId = GeneratedColumn<int>(
    'event_id',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL REFERENCES events(id)ON DELETE SET NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    date,
    courseId,
    roundNumber,
    teeSet,
    courseSetId,
    weather,
    windSpeedMph,
    difficulty,
    notes,
    migrationCanary,
    eventId,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'rounds';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {date, courseId, roundNumber},
  ];
  @override
  RoundsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return RoundsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}id'],
      )!,
      date: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}date'],
      )!,
      courseId: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}course_id'],
      )!,
      roundNumber: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}round_number'],
      )!,
      teeSet: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}tee_set'],
      ),
      courseSetId: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}course_set_id'],
      ),
      weather: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}weather'],
      ),
      windSpeedMph: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}wind_speed_mph'],
      ),
      difficulty: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}difficulty'],
      ),
      notes: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}notes'],
      ),
      migrationCanary: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}migration_canary'],
      ),
      eventId: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}event_id'],
      ),
    );
  }

  @override
  Rounds createAlias(String alias) {
    return Rounds(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'UNIQUE(date, course_id, round_number)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class RoundsData extends DataClass implements Insertable<RoundsData> {
  final int id;
  final String date;
  final int courseId;
  final int roundNumber;
  final String? teeSet;
  final int? courseSetId;
  final String? weather;
  final int? windSpeedMph;
  final String? difficulty;
  final String? notes;
  final String? migrationCanary;
  final int? eventId;
  const RoundsData({
    required this.id,
    required this.date,
    required this.courseId,
    required this.roundNumber,
    this.teeSet,
    this.courseSetId,
    this.weather,
    this.windSpeedMph,
    this.difficulty,
    this.notes,
    this.migrationCanary,
    this.eventId,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['date'] = Variable<String>(date);
    map['course_id'] = Variable<int>(courseId);
    map['round_number'] = Variable<int>(roundNumber);
    if (!nullToAbsent || teeSet != null) {
      map['tee_set'] = Variable<String>(teeSet);
    }
    if (!nullToAbsent || courseSetId != null) {
      map['course_set_id'] = Variable<int>(courseSetId);
    }
    if (!nullToAbsent || weather != null) {
      map['weather'] = Variable<String>(weather);
    }
    if (!nullToAbsent || windSpeedMph != null) {
      map['wind_speed_mph'] = Variable<int>(windSpeedMph);
    }
    if (!nullToAbsent || difficulty != null) {
      map['difficulty'] = Variable<String>(difficulty);
    }
    if (!nullToAbsent || notes != null) {
      map['notes'] = Variable<String>(notes);
    }
    if (!nullToAbsent || migrationCanary != null) {
      map['migration_canary'] = Variable<String>(migrationCanary);
    }
    if (!nullToAbsent || eventId != null) {
      map['event_id'] = Variable<int>(eventId);
    }
    return map;
  }

  RoundsCompanion toCompanion(bool nullToAbsent) {
    return RoundsCompanion(
      id: Value(id),
      date: Value(date),
      courseId: Value(courseId),
      roundNumber: Value(roundNumber),
      teeSet: teeSet == null && nullToAbsent
          ? const Value.absent()
          : Value(teeSet),
      courseSetId: courseSetId == null && nullToAbsent
          ? const Value.absent()
          : Value(courseSetId),
      weather: weather == null && nullToAbsent
          ? const Value.absent()
          : Value(weather),
      windSpeedMph: windSpeedMph == null && nullToAbsent
          ? const Value.absent()
          : Value(windSpeedMph),
      difficulty: difficulty == null && nullToAbsent
          ? const Value.absent()
          : Value(difficulty),
      notes: notes == null && nullToAbsent
          ? const Value.absent()
          : Value(notes),
      migrationCanary: migrationCanary == null && nullToAbsent
          ? const Value.absent()
          : Value(migrationCanary),
      eventId: eventId == null && nullToAbsent
          ? const Value.absent()
          : Value(eventId),
    );
  }

  factory RoundsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return RoundsData(
      id: serializer.fromJson<int>(json['id']),
      date: serializer.fromJson<String>(json['date']),
      courseId: serializer.fromJson<int>(json['courseId']),
      roundNumber: serializer.fromJson<int>(json['roundNumber']),
      teeSet: serializer.fromJson<String?>(json['teeSet']),
      courseSetId: serializer.fromJson<int?>(json['courseSetId']),
      weather: serializer.fromJson<String?>(json['weather']),
      windSpeedMph: serializer.fromJson<int?>(json['windSpeedMph']),
      difficulty: serializer.fromJson<String?>(json['difficulty']),
      notes: serializer.fromJson<String?>(json['notes']),
      migrationCanary: serializer.fromJson<String?>(json['migrationCanary']),
      eventId: serializer.fromJson<int?>(json['eventId']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'date': serializer.toJson<String>(date),
      'courseId': serializer.toJson<int>(courseId),
      'roundNumber': serializer.toJson<int>(roundNumber),
      'teeSet': serializer.toJson<String?>(teeSet),
      'courseSetId': serializer.toJson<int?>(courseSetId),
      'weather': serializer.toJson<String?>(weather),
      'windSpeedMph': serializer.toJson<int?>(windSpeedMph),
      'difficulty': serializer.toJson<String?>(difficulty),
      'notes': serializer.toJson<String?>(notes),
      'migrationCanary': serializer.toJson<String?>(migrationCanary),
      'eventId': serializer.toJson<int?>(eventId),
    };
  }

  RoundsData copyWith({
    int? id,
    String? date,
    int? courseId,
    int? roundNumber,
    Value<String?> teeSet = const Value.absent(),
    Value<int?> courseSetId = const Value.absent(),
    Value<String?> weather = const Value.absent(),
    Value<int?> windSpeedMph = const Value.absent(),
    Value<String?> difficulty = const Value.absent(),
    Value<String?> notes = const Value.absent(),
    Value<String?> migrationCanary = const Value.absent(),
    Value<int?> eventId = const Value.absent(),
  }) => RoundsData(
    id: id ?? this.id,
    date: date ?? this.date,
    courseId: courseId ?? this.courseId,
    roundNumber: roundNumber ?? this.roundNumber,
    teeSet: teeSet.present ? teeSet.value : this.teeSet,
    courseSetId: courseSetId.present ? courseSetId.value : this.courseSetId,
    weather: weather.present ? weather.value : this.weather,
    windSpeedMph: windSpeedMph.present ? windSpeedMph.value : this.windSpeedMph,
    difficulty: difficulty.present ? difficulty.value : this.difficulty,
    notes: notes.present ? notes.value : this.notes,
    migrationCanary: migrationCanary.present
        ? migrationCanary.value
        : this.migrationCanary,
    eventId: eventId.present ? eventId.value : this.eventId,
  );
  RoundsData copyWithCompanion(RoundsCompanion data) {
    return RoundsData(
      id: data.id.present ? data.id.value : this.id,
      date: data.date.present ? data.date.value : this.date,
      courseId: data.courseId.present ? data.courseId.value : this.courseId,
      roundNumber: data.roundNumber.present
          ? data.roundNumber.value
          : this.roundNumber,
      teeSet: data.teeSet.present ? data.teeSet.value : this.teeSet,
      courseSetId: data.courseSetId.present
          ? data.courseSetId.value
          : this.courseSetId,
      weather: data.weather.present ? data.weather.value : this.weather,
      windSpeedMph: data.windSpeedMph.present
          ? data.windSpeedMph.value
          : this.windSpeedMph,
      difficulty: data.difficulty.present
          ? data.difficulty.value
          : this.difficulty,
      notes: data.notes.present ? data.notes.value : this.notes,
      migrationCanary: data.migrationCanary.present
          ? data.migrationCanary.value
          : this.migrationCanary,
      eventId: data.eventId.present ? data.eventId.value : this.eventId,
    );
  }

  @override
  String toString() {
    return (StringBuffer('RoundsData(')
          ..write('id: $id, ')
          ..write('date: $date, ')
          ..write('courseId: $courseId, ')
          ..write('roundNumber: $roundNumber, ')
          ..write('teeSet: $teeSet, ')
          ..write('courseSetId: $courseSetId, ')
          ..write('weather: $weather, ')
          ..write('windSpeedMph: $windSpeedMph, ')
          ..write('difficulty: $difficulty, ')
          ..write('notes: $notes, ')
          ..write('migrationCanary: $migrationCanary, ')
          ..write('eventId: $eventId')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    date,
    courseId,
    roundNumber,
    teeSet,
    courseSetId,
    weather,
    windSpeedMph,
    difficulty,
    notes,
    migrationCanary,
    eventId,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is RoundsData &&
          other.id == this.id &&
          other.date == this.date &&
          other.courseId == this.courseId &&
          other.roundNumber == this.roundNumber &&
          other.teeSet == this.teeSet &&
          other.courseSetId == this.courseSetId &&
          other.weather == this.weather &&
          other.windSpeedMph == this.windSpeedMph &&
          other.difficulty == this.difficulty &&
          other.notes == this.notes &&
          other.migrationCanary == this.migrationCanary &&
          other.eventId == this.eventId);
}

class RoundsCompanion extends UpdateCompanion<RoundsData> {
  final Value<int> id;
  final Value<String> date;
  final Value<int> courseId;
  final Value<int> roundNumber;
  final Value<String?> teeSet;
  final Value<int?> courseSetId;
  final Value<String?> weather;
  final Value<int?> windSpeedMph;
  final Value<String?> difficulty;
  final Value<String?> notes;
  final Value<String?> migrationCanary;
  final Value<int?> eventId;
  const RoundsCompanion({
    this.id = const Value.absent(),
    this.date = const Value.absent(),
    this.courseId = const Value.absent(),
    this.roundNumber = const Value.absent(),
    this.teeSet = const Value.absent(),
    this.courseSetId = const Value.absent(),
    this.weather = const Value.absent(),
    this.windSpeedMph = const Value.absent(),
    this.difficulty = const Value.absent(),
    this.notes = const Value.absent(),
    this.migrationCanary = const Value.absent(),
    this.eventId = const Value.absent(),
  });
  RoundsCompanion.insert({
    this.id = const Value.absent(),
    required String date,
    required int courseId,
    this.roundNumber = const Value.absent(),
    this.teeSet = const Value.absent(),
    this.courseSetId = const Value.absent(),
    this.weather = const Value.absent(),
    this.windSpeedMph = const Value.absent(),
    this.difficulty = const Value.absent(),
    this.notes = const Value.absent(),
    this.migrationCanary = const Value.absent(),
    this.eventId = const Value.absent(),
  }) : date = Value(date),
       courseId = Value(courseId);
  static Insertable<RoundsData> custom({
    Expression<int>? id,
    Expression<String>? date,
    Expression<int>? courseId,
    Expression<int>? roundNumber,
    Expression<String>? teeSet,
    Expression<int>? courseSetId,
    Expression<String>? weather,
    Expression<int>? windSpeedMph,
    Expression<String>? difficulty,
    Expression<String>? notes,
    Expression<String>? migrationCanary,
    Expression<int>? eventId,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (date != null) 'date': date,
      if (courseId != null) 'course_id': courseId,
      if (roundNumber != null) 'round_number': roundNumber,
      if (teeSet != null) 'tee_set': teeSet,
      if (courseSetId != null) 'course_set_id': courseSetId,
      if (weather != null) 'weather': weather,
      if (windSpeedMph != null) 'wind_speed_mph': windSpeedMph,
      if (difficulty != null) 'difficulty': difficulty,
      if (notes != null) 'notes': notes,
      if (migrationCanary != null) 'migration_canary': migrationCanary,
      if (eventId != null) 'event_id': eventId,
    });
  }

  RoundsCompanion copyWith({
    Value<int>? id,
    Value<String>? date,
    Value<int>? courseId,
    Value<int>? roundNumber,
    Value<String?>? teeSet,
    Value<int?>? courseSetId,
    Value<String?>? weather,
    Value<int?>? windSpeedMph,
    Value<String?>? difficulty,
    Value<String?>? notes,
    Value<String?>? migrationCanary,
    Value<int?>? eventId,
  }) {
    return RoundsCompanion(
      id: id ?? this.id,
      date: date ?? this.date,
      courseId: courseId ?? this.courseId,
      roundNumber: roundNumber ?? this.roundNumber,
      teeSet: teeSet ?? this.teeSet,
      courseSetId: courseSetId ?? this.courseSetId,
      weather: weather ?? this.weather,
      windSpeedMph: windSpeedMph ?? this.windSpeedMph,
      difficulty: difficulty ?? this.difficulty,
      notes: notes ?? this.notes,
      migrationCanary: migrationCanary ?? this.migrationCanary,
      eventId: eventId ?? this.eventId,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (date.present) {
      map['date'] = Variable<String>(date.value);
    }
    if (courseId.present) {
      map['course_id'] = Variable<int>(courseId.value);
    }
    if (roundNumber.present) {
      map['round_number'] = Variable<int>(roundNumber.value);
    }
    if (teeSet.present) {
      map['tee_set'] = Variable<String>(teeSet.value);
    }
    if (courseSetId.present) {
      map['course_set_id'] = Variable<int>(courseSetId.value);
    }
    if (weather.present) {
      map['weather'] = Variable<String>(weather.value);
    }
    if (windSpeedMph.present) {
      map['wind_speed_mph'] = Variable<int>(windSpeedMph.value);
    }
    if (difficulty.present) {
      map['difficulty'] = Variable<String>(difficulty.value);
    }
    if (notes.present) {
      map['notes'] = Variable<String>(notes.value);
    }
    if (migrationCanary.present) {
      map['migration_canary'] = Variable<String>(migrationCanary.value);
    }
    if (eventId.present) {
      map['event_id'] = Variable<int>(eventId.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('RoundsCompanion(')
          ..write('id: $id, ')
          ..write('date: $date, ')
          ..write('courseId: $courseId, ')
          ..write('roundNumber: $roundNumber, ')
          ..write('teeSet: $teeSet, ')
          ..write('courseSetId: $courseSetId, ')
          ..write('weather: $weather, ')
          ..write('windSpeedMph: $windSpeedMph, ')
          ..write('difficulty: $difficulty, ')
          ..write('notes: $notes, ')
          ..write('migrationCanary: $migrationCanary, ')
          ..write('eventId: $eventId')
          ..write(')'))
        .toString();
  }
}

class HoleResults extends Table with TableInfo<HoleResults, HoleResultsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  HoleResults(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    hasAutoIncrement: true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
  );
  late final GeneratedColumn<int> roundId = GeneratedColumn<int>(
    'round_id',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES rounds(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<int> holeNumber = GeneratedColumn<int>(
    'hole_number',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (hole_number BETWEEN 1 AND 18)',
  );
  late final GeneratedColumn<int> par = GeneratedColumn<int>(
    'par',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (par BETWEEN 3 AND 5)',
  );
  late final GeneratedColumn<int> score = GeneratedColumn<int>(
    'score',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (score >= 1)',
  );
  late final GeneratedColumn<int> yards = GeneratedColumn<int>(
    'yards',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (yards >= 0)',
  );
  late final GeneratedColumn<int> fairwayHit = GeneratedColumn<int>(
    'fairway_hit',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL CHECK (fairway_hit IN (0, 1))',
  );
  late final GeneratedColumn<int> gir = GeneratedColumn<int>(
    'gir',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (gir IN (0, 1))',
  );
  late final GeneratedColumn<int> putts = GeneratedColumn<int>(
    'putts',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (putts >= 0)',
  );
  late final GeneratedColumn<int> upDownAttempt = GeneratedColumn<int>(
    'up_down_attempt',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (up_down_attempt IN (0, 1))',
  );
  late final GeneratedColumn<int> upDownSuccess = GeneratedColumn<int>(
    'up_down_success',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (up_down_success IN (0, 1))',
  );
  late final GeneratedColumn<int> penaltyStrokes = GeneratedColumn<int>(
    'penalty_strokes',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (penalty_strokes >= 0)',
  );
  late final GeneratedColumn<int> bunkerVisited = GeneratedColumn<int>(
    'bunker_visited',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (bunker_visited IN (0, 1))',
  );
  late final GeneratedColumn<int> sandSave = GeneratedColumn<int>(
    'sand_save',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (sand_save IN (0, 1))',
  );
  late final GeneratedColumn<String> notes = GeneratedColumn<String>(
    'notes',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    roundId,
    holeNumber,
    par,
    score,
    yards,
    fairwayHit,
    gir,
    putts,
    upDownAttempt,
    upDownSuccess,
    penaltyStrokes,
    bunkerVisited,
    sandSave,
    notes,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'hole_results';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {roundId, holeNumber},
  ];
  @override
  HoleResultsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return HoleResultsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}id'],
      )!,
      roundId: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}round_id'],
      )!,
      holeNumber: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}hole_number'],
      )!,
      par: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}par'],
      )!,
      score: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}score'],
      )!,
      yards: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}yards'],
      )!,
      fairwayHit: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}fairway_hit'],
      ),
      gir: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}gir'],
      )!,
      putts: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}putts'],
      )!,
      upDownAttempt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}up_down_attempt'],
      )!,
      upDownSuccess: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}up_down_success'],
      )!,
      penaltyStrokes: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}penalty_strokes'],
      )!,
      bunkerVisited: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}bunker_visited'],
      )!,
      sandSave: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}sand_save'],
      )!,
      notes: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}notes'],
      ),
    );
  }

  @override
  HoleResults createAlias(String alias) {
    return HoleResults(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['UNIQUE(round_id, hole_number)'];
  @override
  bool get dontWriteConstraints => true;
}

class HoleResultsData extends DataClass implements Insertable<HoleResultsData> {
  final int id;
  final int roundId;
  final int holeNumber;
  final int par;
  final int score;
  final int yards;
  final int? fairwayHit;
  final int gir;
  final int putts;
  final int upDownAttempt;
  final int upDownSuccess;
  final int penaltyStrokes;
  final int bunkerVisited;
  final int sandSave;
  final String? notes;
  const HoleResultsData({
    required this.id,
    required this.roundId,
    required this.holeNumber,
    required this.par,
    required this.score,
    required this.yards,
    this.fairwayHit,
    required this.gir,
    required this.putts,
    required this.upDownAttempt,
    required this.upDownSuccess,
    required this.penaltyStrokes,
    required this.bunkerVisited,
    required this.sandSave,
    this.notes,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['round_id'] = Variable<int>(roundId);
    map['hole_number'] = Variable<int>(holeNumber);
    map['par'] = Variable<int>(par);
    map['score'] = Variable<int>(score);
    map['yards'] = Variable<int>(yards);
    if (!nullToAbsent || fairwayHit != null) {
      map['fairway_hit'] = Variable<int>(fairwayHit);
    }
    map['gir'] = Variable<int>(gir);
    map['putts'] = Variable<int>(putts);
    map['up_down_attempt'] = Variable<int>(upDownAttempt);
    map['up_down_success'] = Variable<int>(upDownSuccess);
    map['penalty_strokes'] = Variable<int>(penaltyStrokes);
    map['bunker_visited'] = Variable<int>(bunkerVisited);
    map['sand_save'] = Variable<int>(sandSave);
    if (!nullToAbsent || notes != null) {
      map['notes'] = Variable<String>(notes);
    }
    return map;
  }

  HoleResultsCompanion toCompanion(bool nullToAbsent) {
    return HoleResultsCompanion(
      id: Value(id),
      roundId: Value(roundId),
      holeNumber: Value(holeNumber),
      par: Value(par),
      score: Value(score),
      yards: Value(yards),
      fairwayHit: fairwayHit == null && nullToAbsent
          ? const Value.absent()
          : Value(fairwayHit),
      gir: Value(gir),
      putts: Value(putts),
      upDownAttempt: Value(upDownAttempt),
      upDownSuccess: Value(upDownSuccess),
      penaltyStrokes: Value(penaltyStrokes),
      bunkerVisited: Value(bunkerVisited),
      sandSave: Value(sandSave),
      notes: notes == null && nullToAbsent
          ? const Value.absent()
          : Value(notes),
    );
  }

  factory HoleResultsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return HoleResultsData(
      id: serializer.fromJson<int>(json['id']),
      roundId: serializer.fromJson<int>(json['roundId']),
      holeNumber: serializer.fromJson<int>(json['holeNumber']),
      par: serializer.fromJson<int>(json['par']),
      score: serializer.fromJson<int>(json['score']),
      yards: serializer.fromJson<int>(json['yards']),
      fairwayHit: serializer.fromJson<int?>(json['fairwayHit']),
      gir: serializer.fromJson<int>(json['gir']),
      putts: serializer.fromJson<int>(json['putts']),
      upDownAttempt: serializer.fromJson<int>(json['upDownAttempt']),
      upDownSuccess: serializer.fromJson<int>(json['upDownSuccess']),
      penaltyStrokes: serializer.fromJson<int>(json['penaltyStrokes']),
      bunkerVisited: serializer.fromJson<int>(json['bunkerVisited']),
      sandSave: serializer.fromJson<int>(json['sandSave']),
      notes: serializer.fromJson<String?>(json['notes']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'roundId': serializer.toJson<int>(roundId),
      'holeNumber': serializer.toJson<int>(holeNumber),
      'par': serializer.toJson<int>(par),
      'score': serializer.toJson<int>(score),
      'yards': serializer.toJson<int>(yards),
      'fairwayHit': serializer.toJson<int?>(fairwayHit),
      'gir': serializer.toJson<int>(gir),
      'putts': serializer.toJson<int>(putts),
      'upDownAttempt': serializer.toJson<int>(upDownAttempt),
      'upDownSuccess': serializer.toJson<int>(upDownSuccess),
      'penaltyStrokes': serializer.toJson<int>(penaltyStrokes),
      'bunkerVisited': serializer.toJson<int>(bunkerVisited),
      'sandSave': serializer.toJson<int>(sandSave),
      'notes': serializer.toJson<String?>(notes),
    };
  }

  HoleResultsData copyWith({
    int? id,
    int? roundId,
    int? holeNumber,
    int? par,
    int? score,
    int? yards,
    Value<int?> fairwayHit = const Value.absent(),
    int? gir,
    int? putts,
    int? upDownAttempt,
    int? upDownSuccess,
    int? penaltyStrokes,
    int? bunkerVisited,
    int? sandSave,
    Value<String?> notes = const Value.absent(),
  }) => HoleResultsData(
    id: id ?? this.id,
    roundId: roundId ?? this.roundId,
    holeNumber: holeNumber ?? this.holeNumber,
    par: par ?? this.par,
    score: score ?? this.score,
    yards: yards ?? this.yards,
    fairwayHit: fairwayHit.present ? fairwayHit.value : this.fairwayHit,
    gir: gir ?? this.gir,
    putts: putts ?? this.putts,
    upDownAttempt: upDownAttempt ?? this.upDownAttempt,
    upDownSuccess: upDownSuccess ?? this.upDownSuccess,
    penaltyStrokes: penaltyStrokes ?? this.penaltyStrokes,
    bunkerVisited: bunkerVisited ?? this.bunkerVisited,
    sandSave: sandSave ?? this.sandSave,
    notes: notes.present ? notes.value : this.notes,
  );
  HoleResultsData copyWithCompanion(HoleResultsCompanion data) {
    return HoleResultsData(
      id: data.id.present ? data.id.value : this.id,
      roundId: data.roundId.present ? data.roundId.value : this.roundId,
      holeNumber: data.holeNumber.present
          ? data.holeNumber.value
          : this.holeNumber,
      par: data.par.present ? data.par.value : this.par,
      score: data.score.present ? data.score.value : this.score,
      yards: data.yards.present ? data.yards.value : this.yards,
      fairwayHit: data.fairwayHit.present
          ? data.fairwayHit.value
          : this.fairwayHit,
      gir: data.gir.present ? data.gir.value : this.gir,
      putts: data.putts.present ? data.putts.value : this.putts,
      upDownAttempt: data.upDownAttempt.present
          ? data.upDownAttempt.value
          : this.upDownAttempt,
      upDownSuccess: data.upDownSuccess.present
          ? data.upDownSuccess.value
          : this.upDownSuccess,
      penaltyStrokes: data.penaltyStrokes.present
          ? data.penaltyStrokes.value
          : this.penaltyStrokes,
      bunkerVisited: data.bunkerVisited.present
          ? data.bunkerVisited.value
          : this.bunkerVisited,
      sandSave: data.sandSave.present ? data.sandSave.value : this.sandSave,
      notes: data.notes.present ? data.notes.value : this.notes,
    );
  }

  @override
  String toString() {
    return (StringBuffer('HoleResultsData(')
          ..write('id: $id, ')
          ..write('roundId: $roundId, ')
          ..write('holeNumber: $holeNumber, ')
          ..write('par: $par, ')
          ..write('score: $score, ')
          ..write('yards: $yards, ')
          ..write('fairwayHit: $fairwayHit, ')
          ..write('gir: $gir, ')
          ..write('putts: $putts, ')
          ..write('upDownAttempt: $upDownAttempt, ')
          ..write('upDownSuccess: $upDownSuccess, ')
          ..write('penaltyStrokes: $penaltyStrokes, ')
          ..write('bunkerVisited: $bunkerVisited, ')
          ..write('sandSave: $sandSave, ')
          ..write('notes: $notes')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    roundId,
    holeNumber,
    par,
    score,
    yards,
    fairwayHit,
    gir,
    putts,
    upDownAttempt,
    upDownSuccess,
    penaltyStrokes,
    bunkerVisited,
    sandSave,
    notes,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is HoleResultsData &&
          other.id == this.id &&
          other.roundId == this.roundId &&
          other.holeNumber == this.holeNumber &&
          other.par == this.par &&
          other.score == this.score &&
          other.yards == this.yards &&
          other.fairwayHit == this.fairwayHit &&
          other.gir == this.gir &&
          other.putts == this.putts &&
          other.upDownAttempt == this.upDownAttempt &&
          other.upDownSuccess == this.upDownSuccess &&
          other.penaltyStrokes == this.penaltyStrokes &&
          other.bunkerVisited == this.bunkerVisited &&
          other.sandSave == this.sandSave &&
          other.notes == this.notes);
}

class HoleResultsCompanion extends UpdateCompanion<HoleResultsData> {
  final Value<int> id;
  final Value<int> roundId;
  final Value<int> holeNumber;
  final Value<int> par;
  final Value<int> score;
  final Value<int> yards;
  final Value<int?> fairwayHit;
  final Value<int> gir;
  final Value<int> putts;
  final Value<int> upDownAttempt;
  final Value<int> upDownSuccess;
  final Value<int> penaltyStrokes;
  final Value<int> bunkerVisited;
  final Value<int> sandSave;
  final Value<String?> notes;
  const HoleResultsCompanion({
    this.id = const Value.absent(),
    this.roundId = const Value.absent(),
    this.holeNumber = const Value.absent(),
    this.par = const Value.absent(),
    this.score = const Value.absent(),
    this.yards = const Value.absent(),
    this.fairwayHit = const Value.absent(),
    this.gir = const Value.absent(),
    this.putts = const Value.absent(),
    this.upDownAttempt = const Value.absent(),
    this.upDownSuccess = const Value.absent(),
    this.penaltyStrokes = const Value.absent(),
    this.bunkerVisited = const Value.absent(),
    this.sandSave = const Value.absent(),
    this.notes = const Value.absent(),
  });
  HoleResultsCompanion.insert({
    this.id = const Value.absent(),
    required int roundId,
    required int holeNumber,
    required int par,
    required int score,
    required int yards,
    this.fairwayHit = const Value.absent(),
    required int gir,
    required int putts,
    required int upDownAttempt,
    required int upDownSuccess,
    required int penaltyStrokes,
    required int bunkerVisited,
    required int sandSave,
    this.notes = const Value.absent(),
  }) : roundId = Value(roundId),
       holeNumber = Value(holeNumber),
       par = Value(par),
       score = Value(score),
       yards = Value(yards),
       gir = Value(gir),
       putts = Value(putts),
       upDownAttempt = Value(upDownAttempt),
       upDownSuccess = Value(upDownSuccess),
       penaltyStrokes = Value(penaltyStrokes),
       bunkerVisited = Value(bunkerVisited),
       sandSave = Value(sandSave);
  static Insertable<HoleResultsData> custom({
    Expression<int>? id,
    Expression<int>? roundId,
    Expression<int>? holeNumber,
    Expression<int>? par,
    Expression<int>? score,
    Expression<int>? yards,
    Expression<int>? fairwayHit,
    Expression<int>? gir,
    Expression<int>? putts,
    Expression<int>? upDownAttempt,
    Expression<int>? upDownSuccess,
    Expression<int>? penaltyStrokes,
    Expression<int>? bunkerVisited,
    Expression<int>? sandSave,
    Expression<String>? notes,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (roundId != null) 'round_id': roundId,
      if (holeNumber != null) 'hole_number': holeNumber,
      if (par != null) 'par': par,
      if (score != null) 'score': score,
      if (yards != null) 'yards': yards,
      if (fairwayHit != null) 'fairway_hit': fairwayHit,
      if (gir != null) 'gir': gir,
      if (putts != null) 'putts': putts,
      if (upDownAttempt != null) 'up_down_attempt': upDownAttempt,
      if (upDownSuccess != null) 'up_down_success': upDownSuccess,
      if (penaltyStrokes != null) 'penalty_strokes': penaltyStrokes,
      if (bunkerVisited != null) 'bunker_visited': bunkerVisited,
      if (sandSave != null) 'sand_save': sandSave,
      if (notes != null) 'notes': notes,
    });
  }

  HoleResultsCompanion copyWith({
    Value<int>? id,
    Value<int>? roundId,
    Value<int>? holeNumber,
    Value<int>? par,
    Value<int>? score,
    Value<int>? yards,
    Value<int?>? fairwayHit,
    Value<int>? gir,
    Value<int>? putts,
    Value<int>? upDownAttempt,
    Value<int>? upDownSuccess,
    Value<int>? penaltyStrokes,
    Value<int>? bunkerVisited,
    Value<int>? sandSave,
    Value<String?>? notes,
  }) {
    return HoleResultsCompanion(
      id: id ?? this.id,
      roundId: roundId ?? this.roundId,
      holeNumber: holeNumber ?? this.holeNumber,
      par: par ?? this.par,
      score: score ?? this.score,
      yards: yards ?? this.yards,
      fairwayHit: fairwayHit ?? this.fairwayHit,
      gir: gir ?? this.gir,
      putts: putts ?? this.putts,
      upDownAttempt: upDownAttempt ?? this.upDownAttempt,
      upDownSuccess: upDownSuccess ?? this.upDownSuccess,
      penaltyStrokes: penaltyStrokes ?? this.penaltyStrokes,
      bunkerVisited: bunkerVisited ?? this.bunkerVisited,
      sandSave: sandSave ?? this.sandSave,
      notes: notes ?? this.notes,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (roundId.present) {
      map['round_id'] = Variable<int>(roundId.value);
    }
    if (holeNumber.present) {
      map['hole_number'] = Variable<int>(holeNumber.value);
    }
    if (par.present) {
      map['par'] = Variable<int>(par.value);
    }
    if (score.present) {
      map['score'] = Variable<int>(score.value);
    }
    if (yards.present) {
      map['yards'] = Variable<int>(yards.value);
    }
    if (fairwayHit.present) {
      map['fairway_hit'] = Variable<int>(fairwayHit.value);
    }
    if (gir.present) {
      map['gir'] = Variable<int>(gir.value);
    }
    if (putts.present) {
      map['putts'] = Variable<int>(putts.value);
    }
    if (upDownAttempt.present) {
      map['up_down_attempt'] = Variable<int>(upDownAttempt.value);
    }
    if (upDownSuccess.present) {
      map['up_down_success'] = Variable<int>(upDownSuccess.value);
    }
    if (penaltyStrokes.present) {
      map['penalty_strokes'] = Variable<int>(penaltyStrokes.value);
    }
    if (bunkerVisited.present) {
      map['bunker_visited'] = Variable<int>(bunkerVisited.value);
    }
    if (sandSave.present) {
      map['sand_save'] = Variable<int>(sandSave.value);
    }
    if (notes.present) {
      map['notes'] = Variable<String>(notes.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('HoleResultsCompanion(')
          ..write('id: $id, ')
          ..write('roundId: $roundId, ')
          ..write('holeNumber: $holeNumber, ')
          ..write('par: $par, ')
          ..write('score: $score, ')
          ..write('yards: $yards, ')
          ..write('fairwayHit: $fairwayHit, ')
          ..write('gir: $gir, ')
          ..write('putts: $putts, ')
          ..write('upDownAttempt: $upDownAttempt, ')
          ..write('upDownSuccess: $upDownSuccess, ')
          ..write('penaltyStrokes: $penaltyStrokes, ')
          ..write('bunkerVisited: $bunkerVisited, ')
          ..write('sandSave: $sandSave, ')
          ..write('notes: $notes')
          ..write(')'))
        .toString();
  }
}

class CourseHoles extends Table with TableInfo<CourseHoles, CourseHolesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  CourseHoles(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    hasAutoIncrement: true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
  );
  late final GeneratedColumn<int> courseId = GeneratedColumn<int>(
    'course_id',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES courses(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<int> holeNumber = GeneratedColumn<int>(
    'hole_number',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (hole_number BETWEEN 1 AND 18)',
  );
  late final GeneratedColumn<int> par = GeneratedColumn<int>(
    'par',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (par BETWEEN 3 AND 5)',
  );
  late final GeneratedColumn<int> strokeIndex = GeneratedColumn<int>(
    'stroke_index',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'CHECK (stroke_index BETWEEN 1 AND 18)',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    courseId,
    holeNumber,
    par,
    strokeIndex,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'course_holes';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {courseId, holeNumber},
  ];
  @override
  CourseHolesData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return CourseHolesData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}id'],
      )!,
      courseId: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}course_id'],
      )!,
      holeNumber: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}hole_number'],
      )!,
      par: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}par'],
      )!,
      strokeIndex: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}stroke_index'],
      ),
    );
  }

  @override
  CourseHoles createAlias(String alias) {
    return CourseHoles(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'UNIQUE(course_id, hole_number)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class CourseHolesData extends DataClass implements Insertable<CourseHolesData> {
  final int id;
  final int courseId;
  final int holeNumber;
  final int par;
  final int? strokeIndex;
  const CourseHolesData({
    required this.id,
    required this.courseId,
    required this.holeNumber,
    required this.par,
    this.strokeIndex,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['course_id'] = Variable<int>(courseId);
    map['hole_number'] = Variable<int>(holeNumber);
    map['par'] = Variable<int>(par);
    if (!nullToAbsent || strokeIndex != null) {
      map['stroke_index'] = Variable<int>(strokeIndex);
    }
    return map;
  }

  CourseHolesCompanion toCompanion(bool nullToAbsent) {
    return CourseHolesCompanion(
      id: Value(id),
      courseId: Value(courseId),
      holeNumber: Value(holeNumber),
      par: Value(par),
      strokeIndex: strokeIndex == null && nullToAbsent
          ? const Value.absent()
          : Value(strokeIndex),
    );
  }

  factory CourseHolesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return CourseHolesData(
      id: serializer.fromJson<int>(json['id']),
      courseId: serializer.fromJson<int>(json['courseId']),
      holeNumber: serializer.fromJson<int>(json['holeNumber']),
      par: serializer.fromJson<int>(json['par']),
      strokeIndex: serializer.fromJson<int?>(json['strokeIndex']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'courseId': serializer.toJson<int>(courseId),
      'holeNumber': serializer.toJson<int>(holeNumber),
      'par': serializer.toJson<int>(par),
      'strokeIndex': serializer.toJson<int?>(strokeIndex),
    };
  }

  CourseHolesData copyWith({
    int? id,
    int? courseId,
    int? holeNumber,
    int? par,
    Value<int?> strokeIndex = const Value.absent(),
  }) => CourseHolesData(
    id: id ?? this.id,
    courseId: courseId ?? this.courseId,
    holeNumber: holeNumber ?? this.holeNumber,
    par: par ?? this.par,
    strokeIndex: strokeIndex.present ? strokeIndex.value : this.strokeIndex,
  );
  CourseHolesData copyWithCompanion(CourseHolesCompanion data) {
    return CourseHolesData(
      id: data.id.present ? data.id.value : this.id,
      courseId: data.courseId.present ? data.courseId.value : this.courseId,
      holeNumber: data.holeNumber.present
          ? data.holeNumber.value
          : this.holeNumber,
      par: data.par.present ? data.par.value : this.par,
      strokeIndex: data.strokeIndex.present
          ? data.strokeIndex.value
          : this.strokeIndex,
    );
  }

  @override
  String toString() {
    return (StringBuffer('CourseHolesData(')
          ..write('id: $id, ')
          ..write('courseId: $courseId, ')
          ..write('holeNumber: $holeNumber, ')
          ..write('par: $par, ')
          ..write('strokeIndex: $strokeIndex')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, courseId, holeNumber, par, strokeIndex);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is CourseHolesData &&
          other.id == this.id &&
          other.courseId == this.courseId &&
          other.holeNumber == this.holeNumber &&
          other.par == this.par &&
          other.strokeIndex == this.strokeIndex);
}

class CourseHolesCompanion extends UpdateCompanion<CourseHolesData> {
  final Value<int> id;
  final Value<int> courseId;
  final Value<int> holeNumber;
  final Value<int> par;
  final Value<int?> strokeIndex;
  const CourseHolesCompanion({
    this.id = const Value.absent(),
    this.courseId = const Value.absent(),
    this.holeNumber = const Value.absent(),
    this.par = const Value.absent(),
    this.strokeIndex = const Value.absent(),
  });
  CourseHolesCompanion.insert({
    this.id = const Value.absent(),
    required int courseId,
    required int holeNumber,
    required int par,
    this.strokeIndex = const Value.absent(),
  }) : courseId = Value(courseId),
       holeNumber = Value(holeNumber),
       par = Value(par);
  static Insertable<CourseHolesData> custom({
    Expression<int>? id,
    Expression<int>? courseId,
    Expression<int>? holeNumber,
    Expression<int>? par,
    Expression<int>? strokeIndex,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (courseId != null) 'course_id': courseId,
      if (holeNumber != null) 'hole_number': holeNumber,
      if (par != null) 'par': par,
      if (strokeIndex != null) 'stroke_index': strokeIndex,
    });
  }

  CourseHolesCompanion copyWith({
    Value<int>? id,
    Value<int>? courseId,
    Value<int>? holeNumber,
    Value<int>? par,
    Value<int?>? strokeIndex,
  }) {
    return CourseHolesCompanion(
      id: id ?? this.id,
      courseId: courseId ?? this.courseId,
      holeNumber: holeNumber ?? this.holeNumber,
      par: par ?? this.par,
      strokeIndex: strokeIndex ?? this.strokeIndex,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (courseId.present) {
      map['course_id'] = Variable<int>(courseId.value);
    }
    if (holeNumber.present) {
      map['hole_number'] = Variable<int>(holeNumber.value);
    }
    if (par.present) {
      map['par'] = Variable<int>(par.value);
    }
    if (strokeIndex.present) {
      map['stroke_index'] = Variable<int>(strokeIndex.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('CourseHolesCompanion(')
          ..write('id: $id, ')
          ..write('courseId: $courseId, ')
          ..write('holeNumber: $holeNumber, ')
          ..write('par: $par, ')
          ..write('strokeIndex: $strokeIndex')
          ..write(')'))
        .toString();
  }
}

class CourseSetYards extends Table
    with TableInfo<CourseSetYards, CourseSetYardsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  CourseSetYards(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    hasAutoIncrement: true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
  );
  late final GeneratedColumn<int> courseSetId = GeneratedColumn<int>(
    'course_set_id',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES course_sets(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<int> holeNumber = GeneratedColumn<int>(
    'hole_number',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (hole_number BETWEEN 1 AND 18)',
  );
  late final GeneratedColumn<int> yards = GeneratedColumn<int>(
    'yards',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (yards >= 0)',
  );
  @override
  List<GeneratedColumn> get $columns => [id, courseSetId, holeNumber, yards];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'course_set_yards';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {courseSetId, holeNumber},
  ];
  @override
  CourseSetYardsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return CourseSetYardsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}id'],
      )!,
      courseSetId: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}course_set_id'],
      )!,
      holeNumber: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}hole_number'],
      )!,
      yards: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}yards'],
      )!,
    );
  }

  @override
  CourseSetYards createAlias(String alias) {
    return CourseSetYards(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'UNIQUE(course_set_id, hole_number)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class CourseSetYardsData extends DataClass
    implements Insertable<CourseSetYardsData> {
  final int id;
  final int courseSetId;
  final int holeNumber;
  final int yards;
  const CourseSetYardsData({
    required this.id,
    required this.courseSetId,
    required this.holeNumber,
    required this.yards,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['course_set_id'] = Variable<int>(courseSetId);
    map['hole_number'] = Variable<int>(holeNumber);
    map['yards'] = Variable<int>(yards);
    return map;
  }

  CourseSetYardsCompanion toCompanion(bool nullToAbsent) {
    return CourseSetYardsCompanion(
      id: Value(id),
      courseSetId: Value(courseSetId),
      holeNumber: Value(holeNumber),
      yards: Value(yards),
    );
  }

  factory CourseSetYardsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return CourseSetYardsData(
      id: serializer.fromJson<int>(json['id']),
      courseSetId: serializer.fromJson<int>(json['courseSetId']),
      holeNumber: serializer.fromJson<int>(json['holeNumber']),
      yards: serializer.fromJson<int>(json['yards']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'courseSetId': serializer.toJson<int>(courseSetId),
      'holeNumber': serializer.toJson<int>(holeNumber),
      'yards': serializer.toJson<int>(yards),
    };
  }

  CourseSetYardsData copyWith({
    int? id,
    int? courseSetId,
    int? holeNumber,
    int? yards,
  }) => CourseSetYardsData(
    id: id ?? this.id,
    courseSetId: courseSetId ?? this.courseSetId,
    holeNumber: holeNumber ?? this.holeNumber,
    yards: yards ?? this.yards,
  );
  CourseSetYardsData copyWithCompanion(CourseSetYardsCompanion data) {
    return CourseSetYardsData(
      id: data.id.present ? data.id.value : this.id,
      courseSetId: data.courseSetId.present
          ? data.courseSetId.value
          : this.courseSetId,
      holeNumber: data.holeNumber.present
          ? data.holeNumber.value
          : this.holeNumber,
      yards: data.yards.present ? data.yards.value : this.yards,
    );
  }

  @override
  String toString() {
    return (StringBuffer('CourseSetYardsData(')
          ..write('id: $id, ')
          ..write('courseSetId: $courseSetId, ')
          ..write('holeNumber: $holeNumber, ')
          ..write('yards: $yards')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, courseSetId, holeNumber, yards);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is CourseSetYardsData &&
          other.id == this.id &&
          other.courseSetId == this.courseSetId &&
          other.holeNumber == this.holeNumber &&
          other.yards == this.yards);
}

class CourseSetYardsCompanion extends UpdateCompanion<CourseSetYardsData> {
  final Value<int> id;
  final Value<int> courseSetId;
  final Value<int> holeNumber;
  final Value<int> yards;
  const CourseSetYardsCompanion({
    this.id = const Value.absent(),
    this.courseSetId = const Value.absent(),
    this.holeNumber = const Value.absent(),
    this.yards = const Value.absent(),
  });
  CourseSetYardsCompanion.insert({
    this.id = const Value.absent(),
    required int courseSetId,
    required int holeNumber,
    required int yards,
  }) : courseSetId = Value(courseSetId),
       holeNumber = Value(holeNumber),
       yards = Value(yards);
  static Insertable<CourseSetYardsData> custom({
    Expression<int>? id,
    Expression<int>? courseSetId,
    Expression<int>? holeNumber,
    Expression<int>? yards,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (courseSetId != null) 'course_set_id': courseSetId,
      if (holeNumber != null) 'hole_number': holeNumber,
      if (yards != null) 'yards': yards,
    });
  }

  CourseSetYardsCompanion copyWith({
    Value<int>? id,
    Value<int>? courseSetId,
    Value<int>? holeNumber,
    Value<int>? yards,
  }) {
    return CourseSetYardsCompanion(
      id: id ?? this.id,
      courseSetId: courseSetId ?? this.courseSetId,
      holeNumber: holeNumber ?? this.holeNumber,
      yards: yards ?? this.yards,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (courseSetId.present) {
      map['course_set_id'] = Variable<int>(courseSetId.value);
    }
    if (holeNumber.present) {
      map['hole_number'] = Variable<int>(holeNumber.value);
    }
    if (yards.present) {
      map['yards'] = Variable<int>(yards.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('CourseSetYardsCompanion(')
          ..write('id: $id, ')
          ..write('courseSetId: $courseSetId, ')
          ..write('holeNumber: $holeNumber, ')
          ..write('yards: $yards')
          ..write(')'))
        .toString();
  }
}

class HoleShots extends Table with TableInfo<HoleShots, HoleShotsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  HoleShots(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    hasAutoIncrement: true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
  );
  late final GeneratedColumn<int> holeResultId = GeneratedColumn<int>(
    'hole_result_id',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES hole_results(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<int> shotNumber = GeneratedColumn<int>(
    'shot_number',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (shot_number >= 1)',
  );
  late final GeneratedColumn<String> club = GeneratedColumn<String>(
    'club',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> distanceYards = GeneratedColumn<int>(
    'distance_yards',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'CHECK (distance_yards >= 0)',
  );
  late final GeneratedColumn<String> lie = GeneratedColumn<String>(
    'lie',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> result = GeneratedColumn<String>(
    'result',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    holeResultId,
    shotNumber,
    club,
    distanceYards,
    lie,
    result,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'hole_shots';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {holeResultId, shotNumber},
  ];
  @override
  HoleShotsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return HoleShotsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}id'],
      )!,
      holeResultId: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}hole_result_id'],
      )!,
      shotNumber: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}shot_number'],
      )!,
      club: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}club'],
      ),
      distanceYards: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}distance_yards'],
      ),
      lie: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}lie'],
      ),
      result: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}result'],
      ),
    );
  }

  @override
  HoleShots createAlias(String alias) {
    return HoleShots(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'UNIQUE(hole_result_id, shot_number)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class HoleShotsData extends DataClass implements Insertable<HoleShotsData> {
  final int id;
  final int holeResultId;
  final int shotNumber;
  final String? club;
  final int? distanceYards;
  final String? lie;
  final String? result;
  const HoleShotsData({
    required this.id,
    required this.holeResultId,
    required this.shotNumber,
    this.club,
    this.distanceYards,
    this.lie,
    this.result,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['hole_result_id'] = Variable<int>(holeResultId);
    map['shot_number'] = Variable<int>(shotNumber);
    if (!nullToAbsent || club != null) {
      map['club'] = Variable<String>(club);
    }
    if (!nullToAbsent || distanceYards != null) {
      map['distance_yards'] = Variable<int>(distanceYards);
    }
    if (!nullToAbsent || lie != null) {
      map['lie'] = Variable<String>(lie);
    }
    if (!nullToAbsent || result != null) {
      map['result'] = Variable<String>(result);
    }
    return map;
  }

  HoleShotsCompanion toCompanion(bool nullToAbsent) {
    return HoleShotsCompanion(
      id: Value(id),
      holeResultId: Value(holeResultId),
      shotNumber: Value(shotNumber),
      club: club == null && nullToAbsent ? const Value.absent() : Value(club),
      distanceYards: distanceYards == null && nullToAbsent
          ? const Value.absent()
          : Value(distanceYards),
      lie: lie == null && nullToAbsent ? const Value.absent() : Value(lie),
      result: result == null && nullToAbsent
          ? const Value.absent()
          : Value(result),
    );
  }

  factory HoleShotsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return HoleShotsData(
      id: serializer.fromJson<int>(json['id']),
      holeResultId: serializer.fromJson<int>(json['holeResultId']),
      shotNumber: serializer.fromJson<int>(json['shotNumber']),
      club: serializer.fromJson<String?>(json['club']),
      distanceYards: serializer.fromJson<int?>(json['distanceYards']),
      lie: serializer.fromJson<String?>(json['lie']),
      result: serializer.fromJson<String?>(json['result']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'holeResultId': serializer.toJson<int>(holeResultId),
      'shotNumber': serializer.toJson<int>(shotNumber),
      'club': serializer.toJson<String?>(club),
      'distanceYards': serializer.toJson<int?>(distanceYards),
      'lie': serializer.toJson<String?>(lie),
      'result': serializer.toJson<String?>(result),
    };
  }

  HoleShotsData copyWith({
    int? id,
    int? holeResultId,
    int? shotNumber,
    Value<String?> club = const Value.absent(),
    Value<int?> distanceYards = const Value.absent(),
    Value<String?> lie = const Value.absent(),
    Value<String?> result = const Value.absent(),
  }) => HoleShotsData(
    id: id ?? this.id,
    holeResultId: holeResultId ?? this.holeResultId,
    shotNumber: shotNumber ?? this.shotNumber,
    club: club.present ? club.value : this.club,
    distanceYards: distanceYards.present
        ? distanceYards.value
        : this.distanceYards,
    lie: lie.present ? lie.value : this.lie,
    result: result.present ? result.value : this.result,
  );
  HoleShotsData copyWithCompanion(HoleShotsCompanion data) {
    return HoleShotsData(
      id: data.id.present ? data.id.value : this.id,
      holeResultId: data.holeResultId.present
          ? data.holeResultId.value
          : this.holeResultId,
      shotNumber: data.shotNumber.present
          ? data.shotNumber.value
          : this.shotNumber,
      club: data.club.present ? data.club.value : this.club,
      distanceYards: data.distanceYards.present
          ? data.distanceYards.value
          : this.distanceYards,
      lie: data.lie.present ? data.lie.value : this.lie,
      result: data.result.present ? data.result.value : this.result,
    );
  }

  @override
  String toString() {
    return (StringBuffer('HoleShotsData(')
          ..write('id: $id, ')
          ..write('holeResultId: $holeResultId, ')
          ..write('shotNumber: $shotNumber, ')
          ..write('club: $club, ')
          ..write('distanceYards: $distanceYards, ')
          ..write('lie: $lie, ')
          ..write('result: $result')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    holeResultId,
    shotNumber,
    club,
    distanceYards,
    lie,
    result,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is HoleShotsData &&
          other.id == this.id &&
          other.holeResultId == this.holeResultId &&
          other.shotNumber == this.shotNumber &&
          other.club == this.club &&
          other.distanceYards == this.distanceYards &&
          other.lie == this.lie &&
          other.result == this.result);
}

class HoleShotsCompanion extends UpdateCompanion<HoleShotsData> {
  final Value<int> id;
  final Value<int> holeResultId;
  final Value<int> shotNumber;
  final Value<String?> club;
  final Value<int?> distanceYards;
  final Value<String?> lie;
  final Value<String?> result;
  const HoleShotsCompanion({
    this.id = const Value.absent(),
    this.holeResultId = const Value.absent(),
    this.shotNumber = const Value.absent(),
    this.club = const Value.absent(),
    this.distanceYards = const Value.absent(),
    this.lie = const Value.absent(),
    this.result = const Value.absent(),
  });
  HoleShotsCompanion.insert({
    this.id = const Value.absent(),
    required int holeResultId,
    required int shotNumber,
    this.club = const Value.absent(),
    this.distanceYards = const Value.absent(),
    this.lie = const Value.absent(),
    this.result = const Value.absent(),
  }) : holeResultId = Value(holeResultId),
       shotNumber = Value(shotNumber);
  static Insertable<HoleShotsData> custom({
    Expression<int>? id,
    Expression<int>? holeResultId,
    Expression<int>? shotNumber,
    Expression<String>? club,
    Expression<int>? distanceYards,
    Expression<String>? lie,
    Expression<String>? result,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (holeResultId != null) 'hole_result_id': holeResultId,
      if (shotNumber != null) 'shot_number': shotNumber,
      if (club != null) 'club': club,
      if (distanceYards != null) 'distance_yards': distanceYards,
      if (lie != null) 'lie': lie,
      if (result != null) 'result': result,
    });
  }

  HoleShotsCompanion copyWith({
    Value<int>? id,
    Value<int>? holeResultId,
    Value<int>? shotNumber,
    Value<String?>? club,
    Value<int?>? distanceYards,
    Value<String?>? lie,
    Value<String?>? result,
  }) {
    return HoleShotsCompanion(
      id: id ?? this.id,
      holeResultId: holeResultId ?? this.holeResultId,
      shotNumber: shotNumber ?? this.shotNumber,
      club: club ?? this.club,
      distanceYards: distanceYards ?? this.distanceYards,
      lie: lie ?? this.lie,
      result: result ?? this.result,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (holeResultId.present) {
      map['hole_result_id'] = Variable<int>(holeResultId.value);
    }
    if (shotNumber.present) {
      map['shot_number'] = Variable<int>(shotNumber.value);
    }
    if (club.present) {
      map['club'] = Variable<String>(club.value);
    }
    if (distanceYards.present) {
      map['distance_yards'] = Variable<int>(distanceYards.value);
    }
    if (lie.present) {
      map['lie'] = Variable<String>(lie.value);
    }
    if (result.present) {
      map['result'] = Variable<String>(result.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('HoleShotsCompanion(')
          ..write('id: $id, ')
          ..write('holeResultId: $holeResultId, ')
          ..write('shotNumber: $shotNumber, ')
          ..write('club: $club, ')
          ..write('distanceYards: $distanceYards, ')
          ..write('lie: $lie, ')
          ..write('result: $result')
          ..write(')'))
        .toString();
  }
}

class DatabaseAtV7 extends GeneratedDatabase {
  DatabaseAtV7(QueryExecutor e) : super(e);
  late final Courses courses = Courses(this);
  late final CourseSets courseSets = CourseSets(this);
  late final Events events = Events(this);
  late final Rounds rounds = Rounds(this);
  late final HoleResults holeResults = HoleResults(this);
  late final CourseHoles courseHoles = CourseHoles(this);
  late final CourseSetYards courseSetYards = CourseSetYards(this);
  late final HoleShots holeShots = HoleShots(this);
  late final Index idxRoundsDate = Index(
    'idx_rounds_date',
    'CREATE INDEX idx_rounds_date ON rounds (date)',
  );
  late final Index idxRoundsCourse = Index(
    'idx_rounds_course',
    'CREATE INDEX idx_rounds_course ON rounds (course_id)',
  );
  late final Index idxRoundsEvent = Index(
    'idx_rounds_event',
    'CREATE INDEX idx_rounds_event ON rounds (event_id)',
  );
  late final Index idxRoundsCourseSet = Index(
    'idx_rounds_course_set',
    'CREATE INDEX idx_rounds_course_set ON rounds (course_set_id)',
  );
  late final Index idxHolesRound = Index(
    'idx_holes_round',
    'CREATE INDEX idx_holes_round ON hole_results (round_id)',
  );
  late final Index idxCourseHolesCourse = Index(
    'idx_course_holes_course',
    'CREATE INDEX idx_course_holes_course ON course_holes (course_id)',
  );
  late final Index idxCourseSetsCourse = Index(
    'idx_course_sets_course',
    'CREATE INDEX idx_course_sets_course ON course_sets (course_id)',
  );
  late final Index idxCourseSetYardsSet = Index(
    'idx_course_set_yards_set',
    'CREATE INDEX idx_course_set_yards_set ON course_set_yards (course_set_id)',
  );
  late final Index idxHoleShotsResult = Index(
    'idx_hole_shots_result',
    'CREATE INDEX idx_hole_shots_result ON hole_shots (hole_result_id)',
  );
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    courses,
    courseSets,
    events,
    rounds,
    holeResults,
    courseHoles,
    courseSetYards,
    holeShots,
    idxRoundsDate,
    idxRoundsCourse,
    idxRoundsEvent,
    idxRoundsCourseSet,
    idxHolesRound,
    idxCourseHolesCourse,
    idxCourseSetsCourse,
    idxCourseSetYardsSet,
    idxHoleShotsResult,
  ];
  @override
  StreamQueryUpdateRules get streamUpdateRules => const StreamQueryUpdateRules([
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'courses',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('course_sets', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'course_sets',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('rounds', kind: UpdateKind.update)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'events',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('rounds', kind: UpdateKind.update)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'rounds',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('hole_results', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'courses',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('course_holes', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'course_sets',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('course_set_yards', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'hole_results',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('hole_shots', kind: UpdateKind.delete)],
    ),
  ]);
  @override
  int get schemaVersion => 7;
}
