// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class Courses extends Table with TableInfo<Courses, CoursesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Courses(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    hasAutoIncrement: true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
  );
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> gameTitle = GeneratedColumn<String>(
    'game_title',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [id, name, gameTitle];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'courses';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {name, gameTitle},
  ];
  @override
  CoursesData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return CoursesData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}id'],
      )!,
      name: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}name'],
      )!,
      gameTitle: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}game_title'],
      )!,
    );
  }

  @override
  Courses createAlias(String alias) {
    return Courses(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['UNIQUE(name, game_title)'];
  @override
  bool get dontWriteConstraints => true;
}

class CoursesData extends DataClass implements Insertable<CoursesData> {
  final int id;
  final String name;
  final String gameTitle;
  const CoursesData({
    required this.id,
    required this.name,
    required this.gameTitle,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['name'] = Variable<String>(name);
    map['game_title'] = Variable<String>(gameTitle);
    return map;
  }

  CoursesCompanion toCompanion(bool nullToAbsent) {
    return CoursesCompanion(
      id: Value(id),
      name: Value(name),
      gameTitle: Value(gameTitle),
    );
  }

  factory CoursesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return CoursesData(
      id: serializer.fromJson<int>(json['id']),
      name: serializer.fromJson<String>(json['name']),
      gameTitle: serializer.fromJson<String>(json['gameTitle']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'name': serializer.toJson<String>(name),
      'gameTitle': serializer.toJson<String>(gameTitle),
    };
  }

  CoursesData copyWith({int? id, String? name, String? gameTitle}) =>
      CoursesData(
        id: id ?? this.id,
        name: name ?? this.name,
        gameTitle: gameTitle ?? this.gameTitle,
      );
  CoursesData copyWithCompanion(CoursesCompanion data) {
    return CoursesData(
      id: data.id.present ? data.id.value : this.id,
      name: data.name.present ? data.name.value : this.name,
      gameTitle: data.gameTitle.present ? data.gameTitle.value : this.gameTitle,
    );
  }

  @override
  String toString() {
    return (StringBuffer('CoursesData(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('gameTitle: $gameTitle')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, name, gameTitle);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is CoursesData &&
          other.id == this.id &&
          other.name == this.name &&
          other.gameTitle == this.gameTitle);
}

class CoursesCompanion extends UpdateCompanion<CoursesData> {
  final Value<int> id;
  final Value<String> name;
  final Value<String> gameTitle;
  const CoursesCompanion({
    this.id = const Value.absent(),
    this.name = const Value.absent(),
    this.gameTitle = const Value.absent(),
  });
  CoursesCompanion.insert({
    this.id = const Value.absent(),
    required String name,
    required String gameTitle,
  }) : name = Value(name),
       gameTitle = Value(gameTitle);
  static Insertable<CoursesData> custom({
    Expression<int>? id,
    Expression<String>? name,
    Expression<String>? gameTitle,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (gameTitle != null) 'game_title': gameTitle,
    });
  }

  CoursesCompanion copyWith({
    Value<int>? id,
    Value<String>? name,
    Value<String>? gameTitle,
  }) {
    return CoursesCompanion(
      id: id ?? this.id,
      name: name ?? this.name,
      gameTitle: gameTitle ?? this.gameTitle,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (name.present) {
      map['name'] = Variable<String>(name.value);
    }
    if (gameTitle.present) {
      map['game_title'] = Variable<String>(gameTitle.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('CoursesCompanion(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('gameTitle: $gameTitle')
          ..write(')'))
        .toString();
  }
}

class Events extends Table with TableInfo<Events, EventsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Events(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    hasAutoIncrement: true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
  );
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> season = GeneratedColumn<int>(
    'season',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 1',
    defaultValue: const CustomExpression('1'),
  );
  late final GeneratedColumn<int> finishPosition = GeneratedColumn<int>(
    'finish_position',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> tied = GeneratedColumn<int>(
    'tied',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0 CHECK (tied IN (0, 1))',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<int> missedCut = GeneratedColumn<int>(
    'missed_cut',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0 CHECK (missed_cut IN (0, 1))',
    defaultValue: const CustomExpression('0'),
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    name,
    season,
    finishPosition,
    tied,
    missedCut,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'events';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {name, season},
  ];
  @override
  EventsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return EventsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}id'],
      )!,
      name: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}name'],
      )!,
      season: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}season'],
      )!,
      finishPosition: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}finish_position'],
      ),
      tied: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}tied'],
      )!,
      missedCut: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}missed_cut'],
      )!,
    );
  }

  @override
  Events createAlias(String alias) {
    return Events(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['UNIQUE(name, season)'];
  @override
  bool get dontWriteConstraints => true;
}

class EventsData extends DataClass implements Insertable<EventsData> {
  final int id;
  final String name;
  final int season;
  final int? finishPosition;
  final int tied;
  final int missedCut;
  const EventsData({
    required this.id,
    required this.name,
    required this.season,
    this.finishPosition,
    required this.tied,
    required this.missedCut,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['name'] = Variable<String>(name);
    map['season'] = Variable<int>(season);
    if (!nullToAbsent || finishPosition != null) {
      map['finish_position'] = Variable<int>(finishPosition);
    }
    map['tied'] = Variable<int>(tied);
    map['missed_cut'] = Variable<int>(missedCut);
    return map;
  }

  EventsCompanion toCompanion(bool nullToAbsent) {
    return EventsCompanion(
      id: Value(id),
      name: Value(name),
      season: Value(season),
      finishPosition: finishPosition == null && nullToAbsent
          ? const Value.absent()
          : Value(finishPosition),
      tied: Value(tied),
      missedCut: Value(missedCut),
    );
  }

  factory EventsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return EventsData(
      id: serializer.fromJson<int>(json['id']),
      name: serializer.fromJson<String>(json['name']),
      season: serializer.fromJson<int>(json['season']),
      finishPosition: serializer.fromJson<int?>(json['finishPosition']),
      tied: serializer.fromJson<int>(json['tied']),
      missedCut: serializer.fromJson<int>(json['missedCut']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'name': serializer.toJson<String>(name),
      'season': serializer.toJson<int>(season),
      'finishPosition': serializer.toJson<int?>(finishPosition),
      'tied': serializer.toJson<int>(tied),
      'missedCut': serializer.toJson<int>(missedCut),
    };
  }

  EventsData copyWith({
    int? id,
    String? name,
    int? season,
    Value<int?> finishPosition = const Value.absent(),
    int? tied,
    int? missedCut,
  }) => EventsData(
    id: id ?? this.id,
    name: name ?? this.name,
    season: season ?? this.season,
    finishPosition: finishPosition.present
        ? finishPosition.value
        : this.finishPosition,
    tied: tied ?? this.tied,
    missedCut: missedCut ?? this.missedCut,
  );
  EventsData copyWithCompanion(EventsCompanion data) {
    return EventsData(
      id: data.id.present ? data.id.value : this.id,
      name: data.name.present ? data.name.value : this.name,
      season: data.season.present ? data.season.value : this.season,
      finishPosition: data.finishPosition.present
          ? data.finishPosition.value
          : this.finishPosition,
      tied: data.tied.present ? data.tied.value : this.tied,
      missedCut: data.missedCut.present ? data.missedCut.value : this.missedCut,
    );
  }

  @override
  String toString() {
    return (StringBuffer('EventsData(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('season: $season, ')
          ..write('finishPosition: $finishPosition, ')
          ..write('tied: $tied, ')
          ..write('missedCut: $missedCut')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode =>
      Object.hash(id, name, season, finishPosition, tied, missedCut);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is EventsData &&
          other.id == this.id &&
          other.name == this.name &&
          other.season == this.season &&
          other.finishPosition == this.finishPosition &&
          other.tied == this.tied &&
          other.missedCut == this.missedCut);
}

class EventsCompanion extends UpdateCompanion<EventsData> {
  final Value<int> id;
  final Value<String> name;
  final Value<int> season;
  final Value<int?> finishPosition;
  final Value<int> tied;
  final Value<int> missedCut;
  const EventsCompanion({
    this.id = const Value.absent(),
    this.name = const Value.absent(),
    this.season = const Value.absent(),
    this.finishPosition = const Value.absent(),
    this.tied = const Value.absent(),
    this.missedCut = const Value.absent(),
  });
  EventsCompanion.insert({
    this.id = const Value.absent(),
    required String name,
    this.season = const Value.absent(),
    this.finishPosition = const Value.absent(),
    this.tied = const Value.absent(),
    this.missedCut = const Value.absent(),
  }) : name = Value(name);
  static Insertable<EventsData> custom({
    Expression<int>? id,
    Expression<String>? name,
    Expression<int>? season,
    Expression<int>? finishPosition,
    Expression<int>? tied,
    Expression<int>? missedCut,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (season != null) 'season': season,
      if (finishPosition != null) 'finish_position': finishPosition,
      if (tied != null) 'tied': tied,
      if (missedCut != null) 'missed_cut': missedCut,
    });
  }

  EventsCompanion copyWith({
    Value<int>? id,
    Value<String>? name,
    Value<int>? season,
    Value<int?>? finishPosition,
    Value<int>? tied,
    Value<int>? missedCut,
  }) {
    return EventsCompanion(
      id: id ?? this.id,
      name: name ?? this.name,
      season: season ?? this.season,
      finishPosition: finishPosition ?? this.finishPosition,
      tied: tied ?? this.tied,
      missedCut: missedCut ?? this.missedCut,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (name.present) {
      map['name'] = Variable<String>(name.value);
    }
    if (season.present) {
      map['season'] = Variable<int>(season.value);
    }
    if (finishPosition.present) {
      map['finish_position'] = Variable<int>(finishPosition.value);
    }
    if (tied.present) {
      map['tied'] = Variable<int>(tied.value);
    }
    if (missedCut.present) {
      map['missed_cut'] = Variable<int>(missedCut.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('EventsCompanion(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('season: $season, ')
          ..write('finishPosition: $finishPosition, ')
          ..write('tied: $tied, ')
          ..write('missedCut: $missedCut')
          ..write(')'))
        .toString();
  }
}

class Rounds extends Table with TableInfo<Rounds, RoundsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Rounds(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    hasAutoIncrement: true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
  );
  late final GeneratedColumn<String> date = GeneratedColumn<String>(
    'date',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> courseId = GeneratedColumn<int>(
    'course_id',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES courses(id)ON DELETE RESTRICT',
  );
  late final GeneratedColumn<int> roundNumber = GeneratedColumn<int>(
    'round_number',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 1',
    defaultValue: const CustomExpression('1'),
  );
  late final GeneratedColumn<String> teeSet = GeneratedColumn<String>(
    'tee_set',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> weather = GeneratedColumn<String>(
    'weather',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> windSpeedMph = GeneratedColumn<int>(
    'wind_speed_mph',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> difficulty = GeneratedColumn<String>(
    'difficulty',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> notes = GeneratedColumn<String>(
    'notes',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> migrationCanary = GeneratedColumn<String>(
    'migration_canary',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> eventId = GeneratedColumn<int>(
    'event_id',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL REFERENCES events(id)ON DELETE SET NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    date,
    courseId,
    roundNumber,
    teeSet,
    weather,
    windSpeedMph,
    difficulty,
    notes,
    migrationCanary,
    eventId,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'rounds';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {date, courseId, roundNumber},
  ];
  @override
  RoundsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return RoundsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}id'],
      )!,
      date: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}date'],
      )!,
      courseId: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}course_id'],
      )!,
      roundNumber: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}round_number'],
      )!,
      teeSet: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}tee_set'],
      ),
      weather: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}weather'],
      ),
      windSpeedMph: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}wind_speed_mph'],
      ),
      difficulty: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}difficulty'],
      ),
      notes: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}notes'],
      ),
      migrationCanary: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}migration_canary'],
      ),
      eventId: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}event_id'],
      ),
    );
  }

  @override
  Rounds createAlias(String alias) {
    return Rounds(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'UNIQUE(date, course_id, round_number)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class RoundsData extends DataClass implements Insertable<RoundsData> {
  final int id;
  final String date;
  final int courseId;
  final int roundNumber;
  final String? teeSet;
  final String? weather;
  final int? windSpeedMph;
  final String? difficulty;
  final String? notes;
  final String? migrationCanary;
  final int? eventId;
  const RoundsData({
    required this.id,
    required this.date,
    required this.courseId,
    required this.roundNumber,
    this.teeSet,
    this.weather,
    this.windSpeedMph,
    this.difficulty,
    this.notes,
    this.migrationCanary,
    this.eventId,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['date'] = Variable<String>(date);
    map['course_id'] = Variable<int>(courseId);
    map['round_number'] = Variable<int>(roundNumber);
    if (!nullToAbsent || teeSet != null) {
      map['tee_set'] = Variable<String>(teeSet);
    }
    if (!nullToAbsent || weather != null) {
      map['weather'] = Variable<String>(weather);
    }
    if (!nullToAbsent || windSpeedMph != null) {
      map['wind_speed_mph'] = Variable<int>(windSpeedMph);
    }
    if (!nullToAbsent || difficulty != null) {
      map['difficulty'] = Variable<String>(difficulty);
    }
    if (!nullToAbsent || notes != null) {
      map['notes'] = Variable<String>(notes);
    }
    if (!nullToAbsent || migrationCanary != null) {
      map['migration_canary'] = Variable<String>(migrationCanary);
    }
    if (!nullToAbsent || eventId != null) {
      map['event_id'] = Variable<int>(eventId);
    }
    return map;
  }

  RoundsCompanion toCompanion(bool nullToAbsent) {
    return RoundsCompanion(
      id: Value(id),
      date: Value(date),
      courseId: Value(courseId),
      roundNumber: Value(roundNumber),
      teeSet: teeSet == null && nullToAbsent
          ? const Value.absent()
          : Value(teeSet),
      weather: weather == null && nullToAbsent
          ? const Value.absent()
          : Value(weather),
      windSpeedMph: windSpeedMph == null && nullToAbsent
          ? const Value.absent()
          : Value(windSpeedMph),
      difficulty: difficulty == null && nullToAbsent
          ? const Value.absent()
          : Value(difficulty),
      notes: notes == null && nullToAbsent
          ? const Value.absent()
          : Value(notes),
      migrationCanary: migrationCanary == null && nullToAbsent
          ? const Value.absent()
          : Value(migrationCanary),
      eventId: eventId == null && nullToAbsent
          ? const Value.absent()
          : Value(eventId),
    );
  }

  factory RoundsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return RoundsData(
      id: serializer.fromJson<int>(json['id']),
      date: serializer.fromJson<String>(json['date']),
      courseId: serializer.fromJson<int>(json['courseId']),
      roundNumber: serializer.fromJson<int>(json['roundNumber']),
      teeSet: serializer.fromJson<String?>(json['teeSet']),
      weather: serializer.fromJson<String?>(json['weather']),
      windSpeedMph: serializer.fromJson<int?>(json['windSpeedMph']),
      difficulty: serializer.fromJson<String?>(json['difficulty']),
      notes: serializer.fromJson<String?>(json['notes']),
      migrationCanary: serializer.fromJson<String?>(json['migrationCanary']),
      eventId: serializer.fromJson<int?>(json['eventId']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'date': serializer.toJson<String>(date),
      'courseId': serializer.toJson<int>(courseId),
      'roundNumber': serializer.toJson<int>(roundNumber),
      'teeSet': serializer.toJson<String?>(teeSet),
      'weather': serializer.toJson<String?>(weather),
      'windSpeedMph': serializer.toJson<int?>(windSpeedMph),
      'difficulty': serializer.toJson<String?>(difficulty),
      'notes': serializer.toJson<String?>(notes),
      'migrationCanary': serializer.toJson<String?>(migrationCanary),
      'eventId': serializer.toJson<int?>(eventId),
    };
  }

  RoundsData copyWith({
    int? id,
    String? date,
    int? courseId,
    int? roundNumber,
    Value<String?> teeSet = const Value.absent(),
    Value<String?> weather = const Value.absent(),
    Value<int?> windSpeedMph = const Value.absent(),
    Value<String?> difficulty = const Value.absent(),
    Value<String?> notes = const Value.absent(),
    Value<String?> migrationCanary = const Value.absent(),
    Value<int?> eventId = const Value.absent(),
  }) => RoundsData(
    id: id ?? this.id,
    date: date ?? this.date,
    courseId: courseId ?? this.courseId,
    roundNumber: roundNumber ?? this.roundNumber,
    teeSet: teeSet.present ? teeSet.value : this.teeSet,
    weather: weather.present ? weather.value : this.weather,
    windSpeedMph: windSpeedMph.present ? windSpeedMph.value : this.windSpeedMph,
    difficulty: difficulty.present ? difficulty.value : this.difficulty,
    notes: notes.present ? notes.value : this.notes,
    migrationCanary: migrationCanary.present
        ? migrationCanary.value
        : this.migrationCanary,
    eventId: eventId.present ? eventId.value : this.eventId,
  );
  RoundsData copyWithCompanion(RoundsCompanion data) {
    return RoundsData(
      id: data.id.present ? data.id.value : this.id,
      date: data.date.present ? data.date.value : this.date,
      courseId: data.courseId.present ? data.courseId.value : this.courseId,
      roundNumber: data.roundNumber.present
          ? data.roundNumber.value
          : this.roundNumber,
      teeSet: data.teeSet.present ? data.teeSet.value : this.teeSet,
      weather: data.weather.present ? data.weather.value : this.weather,
      windSpeedMph: data.windSpeedMph.present
          ? data.windSpeedMph.value
          : this.windSpeedMph,
      difficulty: data.difficulty.present
          ? data.difficulty.value
          : this.difficulty,
      notes: data.notes.present ? data.notes.value : this.notes,
      migrationCanary: data.migrationCanary.present
          ? data.migrationCanary.value
          : this.migrationCanary,
      eventId: data.eventId.present ? data.eventId.value : this.eventId,
    );
  }

  @override
  String toString() {
    return (StringBuffer('RoundsData(')
          ..write('id: $id, ')
          ..write('date: $date, ')
          ..write('courseId: $courseId, ')
          ..write('roundNumber: $roundNumber, ')
          ..write('teeSet: $teeSet, ')
          ..write('weather: $weather, ')
          ..write('windSpeedMph: $windSpeedMph, ')
          ..write('difficulty: $difficulty, ')
          ..write('notes: $notes, ')
          ..write('migrationCanary: $migrationCanary, ')
          ..write('eventId: $eventId')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    date,
    courseId,
    roundNumber,
    teeSet,
    weather,
    windSpeedMph,
    difficulty,
    notes,
    migrationCanary,
    eventId,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is RoundsData &&
          other.id == this.id &&
          other.date == this.date &&
          other.courseId == this.courseId &&
          other.roundNumber == this.roundNumber &&
          other.teeSet == this.teeSet &&
          other.weather == this.weather &&
          other.windSpeedMph == this.windSpeedMph &&
          other.difficulty == this.difficulty &&
          other.notes == this.notes &&
          other.migrationCanary == this.migrationCanary &&
          other.eventId == this.eventId);
}

class RoundsCompanion extends UpdateCompanion<RoundsData> {
  final Value<int> id;
  final Value<String> date;
  final Value<int> courseId;
  final Value<int> roundNumber;
  final Value<String?> teeSet;
  final Value<String?> weather;
  final Value<int?> windSpeedMph;
  final Value<String?> difficulty;
  final Value<String?> notes;
  final Value<String?> migrationCanary;
  final Value<int?> eventId;
  const RoundsCompanion({
    this.id = const Value.absent(),
    this.date = const Value.absent(),
    this.courseId = const Value.absent(),
    this.roundNumber = const Value.absent(),
    this.teeSet = const Value.absent(),
    this.weather = const Value.absent(),
    this.windSpeedMph = const Value.absent(),
    this.difficulty = const Value.absent(),
    this.notes = const Value.absent(),
    this.migrationCanary = const Value.absent(),
    this.eventId = const Value.absent(),
  });
  RoundsCompanion.insert({
    this.id = const Value.absent(),
    required String date,
    required int courseId,
    this.roundNumber = const Value.absent(),
    this.teeSet = const Value.absent(),
    this.weather = const Value.absent(),
    this.windSpeedMph = const Value.absent(),
    this.difficulty = const Value.absent(),
    this.notes = const Value.absent(),
    this.migrationCanary = const Value.absent(),
    this.eventId = const Value.absent(),
  }) : date = Value(date),
       courseId = Value(courseId);
  static Insertable<RoundsData> custom({
    Expression<int>? id,
    Expression<String>? date,
    Expression<int>? courseId,
    Expression<int>? roundNumber,
    Expression<String>? teeSet,
    Expression<String>? weather,
    Expression<int>? windSpeedMph,
    Expression<String>? difficulty,
    Expression<String>? notes,
    Expression<String>? migrationCanary,
    Expression<int>? eventId,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (date != null) 'date': date,
      if (courseId != null) 'course_id': courseId,
      if (roundNumber != null) 'round_number': roundNumber,
      if (teeSet != null) 'tee_set': teeSet,
      if (weather != null) 'weather': weather,
      if (windSpeedMph != null) 'wind_speed_mph': windSpeedMph,
      if (difficulty != null) 'difficulty': difficulty,
      if (notes != null) 'notes': notes,
      if (migrationCanary != null) 'migration_canary': migrationCanary,
      if (eventId != null) 'event_id': eventId,
    });
  }

  RoundsCompanion copyWith({
    Value<int>? id,
    Value<String>? date,
    Value<int>? courseId,
    Value<int>? roundNumber,
    Value<String?>? teeSet,
    Value<String?>? weather,
    Value<int?>? windSpeedMph,
    Value<String?>? difficulty,
    Value<String?>? notes,
    Value<String?>? migrationCanary,
    Value<int?>? eventId,
  }) {
    return RoundsCompanion(
      id: id ?? this.id,
      date: date ?? this.date,
      courseId: courseId ?? this.courseId,
      roundNumber: roundNumber ?? this.roundNumber,
      teeSet: teeSet ?? this.teeSet,
      weather: weather ?? this.weather,
      windSpeedMph: windSpeedMph ?? this.windSpeedMph,
      difficulty: difficulty ?? this.difficulty,
      notes: notes ?? this.notes,
      migrationCanary: migrationCanary ?? this.migrationCanary,
      eventId: eventId ?? this.eventId,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (date.present) {
      map['date'] = Variable<String>(date.value);
    }
    if (courseId.present) {
      map['course_id'] = Variable<int>(courseId.value);
    }
    if (roundNumber.present) {
      map['round_number'] = Variable<int>(roundNumber.value);
    }
    if (teeSet.present) {
      map['tee_set'] = Variable<String>(teeSet.value);
    }
    if (weather.present) {
      map['weather'] = Variable<String>(weather.value);
    }
    if (windSpeedMph.present) {
      map['wind_speed_mph'] = Variable<int>(windSpeedMph.value);
    }
    if (difficulty.present) {
      map['difficulty'] = Variable<String>(difficulty.value);
    }
    if (notes.present) {
      map['notes'] = Variable<String>(notes.value);
    }
    if (migrationCanary.present) {
      map['migration_canary'] = Variable<String>(migrationCanary.value);
    }
    if (eventId.present) {
      map['event_id'] = Variable<int>(eventId.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('RoundsCompanion(')
          ..write('id: $id, ')
          ..write('date: $date, ')
          ..write('courseId: $courseId, ')
          ..write('roundNumber: $roundNumber, ')
          ..write('teeSet: $teeSet, ')
          ..write('weather: $weather, ')
          ..write('windSpeedMph: $windSpeedMph, ')
          ..write('difficulty: $difficulty, ')
          ..write('notes: $notes, ')
          ..write('migrationCanary: $migrationCanary, ')
          ..write('eventId: $eventId')
          ..write(')'))
        .toString();
  }
}

class HoleResults extends Table with TableInfo<HoleResults, HoleResultsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  HoleResults(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    hasAutoIncrement: true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
  );
  late final GeneratedColumn<int> roundId = GeneratedColumn<int>(
    'round_id',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES rounds(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<int> holeNumber = GeneratedColumn<int>(
    'hole_number',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (hole_number BETWEEN 1 AND 18)',
  );
  late final GeneratedColumn<int> par = GeneratedColumn<int>(
    'par',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (par BETWEEN 3 AND 5)',
  );
  late final GeneratedColumn<int> score = GeneratedColumn<int>(
    'score',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (score >= 1)',
  );
  late final GeneratedColumn<int> yards = GeneratedColumn<int>(
    'yards',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (yards >= 0)',
  );
  late final GeneratedColumn<int> fairwayHit = GeneratedColumn<int>(
    'fairway_hit',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL CHECK (fairway_hit IN (0, 1))',
  );
  late final GeneratedColumn<int> gir = GeneratedColumn<int>(
    'gir',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (gir IN (0, 1))',
  );
  late final GeneratedColumn<int> putts = GeneratedColumn<int>(
    'putts',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (putts >= 0)',
  );
  late final GeneratedColumn<int> upDownAttempt = GeneratedColumn<int>(
    'up_down_attempt',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (up_down_attempt IN (0, 1))',
  );
  late final GeneratedColumn<int> upDownSuccess = GeneratedColumn<int>(
    'up_down_success',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (up_down_success IN (0, 1))',
  );
  late final GeneratedColumn<int> penaltyStrokes = GeneratedColumn<int>(
    'penalty_strokes',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (penalty_strokes >= 0)',
  );
  late final GeneratedColumn<int> bunkerVisited = GeneratedColumn<int>(
    'bunker_visited',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (bunker_visited IN (0, 1))',
  );
  late final GeneratedColumn<int> sandSave = GeneratedColumn<int>(
    'sand_save',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (sand_save IN (0, 1))',
  );
  late final GeneratedColumn<int> driveDistanceYards = GeneratedColumn<int>(
    'drive_distance_yards',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (drive_distance_yards >= 0)',
  );
  late final GeneratedColumn<int> approachDistanceYards = GeneratedColumn<int>(
    'approach_distance_yards',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'CHECK (approach_distance_yards >= 0)',
  );
  late final GeneratedColumn<String> teeClub = GeneratedColumn<String>(
    'tee_club',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> notes = GeneratedColumn<String>(
    'notes',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    roundId,
    holeNumber,
    par,
    score,
    yards,
    fairwayHit,
    gir,
    putts,
    upDownAttempt,
    upDownSuccess,
    penaltyStrokes,
    bunkerVisited,
    sandSave,
    driveDistanceYards,
    approachDistanceYards,
    teeClub,
    notes,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'hole_results';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {roundId, holeNumber},
  ];
  @override
  HoleResultsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return HoleResultsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}id'],
      )!,
      roundId: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}round_id'],
      )!,
      holeNumber: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}hole_number'],
      )!,
      par: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}par'],
      )!,
      score: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}score'],
      )!,
      yards: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}yards'],
      )!,
      fairwayHit: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}fairway_hit'],
      ),
      gir: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}gir'],
      )!,
      putts: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}putts'],
      )!,
      upDownAttempt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}up_down_attempt'],
      )!,
      upDownSuccess: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}up_down_success'],
      )!,
      penaltyStrokes: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}penalty_strokes'],
      )!,
      bunkerVisited: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}bunker_visited'],
      )!,
      sandSave: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}sand_save'],
      )!,
      driveDistanceYards: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}drive_distance_yards'],
      )!,
      approachDistanceYards: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}approach_distance_yards'],
      ),
      teeClub: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}tee_club'],
      ),
      notes: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}notes'],
      ),
    );
  }

  @override
  HoleResults createAlias(String alias) {
    return HoleResults(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['UNIQUE(round_id, hole_number)'];
  @override
  bool get dontWriteConstraints => true;
}

class HoleResultsData extends DataClass implements Insertable<HoleResultsData> {
  final int id;
  final int roundId;
  final int holeNumber;
  final int par;
  final int score;
  final int yards;
  final int? fairwayHit;
  final int gir;
  final int putts;
  final int upDownAttempt;
  final int upDownSuccess;
  final int penaltyStrokes;
  final int bunkerVisited;
  final int sandSave;
  final int driveDistanceYards;
  final int? approachDistanceYards;
  final String? teeClub;
  final String? notes;
  const HoleResultsData({
    required this.id,
    required this.roundId,
    required this.holeNumber,
    required this.par,
    required this.score,
    required this.yards,
    this.fairwayHit,
    required this.gir,
    required this.putts,
    required this.upDownAttempt,
    required this.upDownSuccess,
    required this.penaltyStrokes,
    required this.bunkerVisited,
    required this.sandSave,
    required this.driveDistanceYards,
    this.approachDistanceYards,
    this.teeClub,
    this.notes,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['round_id'] = Variable<int>(roundId);
    map['hole_number'] = Variable<int>(holeNumber);
    map['par'] = Variable<int>(par);
    map['score'] = Variable<int>(score);
    map['yards'] = Variable<int>(yards);
    if (!nullToAbsent || fairwayHit != null) {
      map['fairway_hit'] = Variable<int>(fairwayHit);
    }
    map['gir'] = Variable<int>(gir);
    map['putts'] = Variable<int>(putts);
    map['up_down_attempt'] = Variable<int>(upDownAttempt);
    map['up_down_success'] = Variable<int>(upDownSuccess);
    map['penalty_strokes'] = Variable<int>(penaltyStrokes);
    map['bunker_visited'] = Variable<int>(bunkerVisited);
    map['sand_save'] = Variable<int>(sandSave);
    map['drive_distance_yards'] = Variable<int>(driveDistanceYards);
    if (!nullToAbsent || approachDistanceYards != null) {
      map['approach_distance_yards'] = Variable<int>(approachDistanceYards);
    }
    if (!nullToAbsent || teeClub != null) {
      map['tee_club'] = Variable<String>(teeClub);
    }
    if (!nullToAbsent || notes != null) {
      map['notes'] = Variable<String>(notes);
    }
    return map;
  }

  HoleResultsCompanion toCompanion(bool nullToAbsent) {
    return HoleResultsCompanion(
      id: Value(id),
      roundId: Value(roundId),
      holeNumber: Value(holeNumber),
      par: Value(par),
      score: Value(score),
      yards: Value(yards),
      fairwayHit: fairwayHit == null && nullToAbsent
          ? const Value.absent()
          : Value(fairwayHit),
      gir: Value(gir),
      putts: Value(putts),
      upDownAttempt: Value(upDownAttempt),
      upDownSuccess: Value(upDownSuccess),
      penaltyStrokes: Value(penaltyStrokes),
      bunkerVisited: Value(bunkerVisited),
      sandSave: Value(sandSave),
      driveDistanceYards: Value(driveDistanceYards),
      approachDistanceYards: approachDistanceYards == null && nullToAbsent
          ? const Value.absent()
          : Value(approachDistanceYards),
      teeClub: teeClub == null && nullToAbsent
          ? const Value.absent()
          : Value(teeClub),
      notes: notes == null && nullToAbsent
          ? const Value.absent()
          : Value(notes),
    );
  }

  factory HoleResultsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return HoleResultsData(
      id: serializer.fromJson<int>(json['id']),
      roundId: serializer.fromJson<int>(json['roundId']),
      holeNumber: serializer.fromJson<int>(json['holeNumber']),
      par: serializer.fromJson<int>(json['par']),
      score: serializer.fromJson<int>(json['score']),
      yards: serializer.fromJson<int>(json['yards']),
      fairwayHit: serializer.fromJson<int?>(json['fairwayHit']),
      gir: serializer.fromJson<int>(json['gir']),
      putts: serializer.fromJson<int>(json['putts']),
      upDownAttempt: serializer.fromJson<int>(json['upDownAttempt']),
      upDownSuccess: serializer.fromJson<int>(json['upDownSuccess']),
      penaltyStrokes: serializer.fromJson<int>(json['penaltyStrokes']),
      bunkerVisited: serializer.fromJson<int>(json['bunkerVisited']),
      sandSave: serializer.fromJson<int>(json['sandSave']),
      driveDistanceYards: serializer.fromJson<int>(json['driveDistanceYards']),
      approachDistanceYards: serializer.fromJson<int?>(
        json['approachDistanceYards'],
      ),
      teeClub: serializer.fromJson<String?>(json['teeClub']),
      notes: serializer.fromJson<String?>(json['notes']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'roundId': serializer.toJson<int>(roundId),
      'holeNumber': serializer.toJson<int>(holeNumber),
      'par': serializer.toJson<int>(par),
      'score': serializer.toJson<int>(score),
      'yards': serializer.toJson<int>(yards),
      'fairwayHit': serializer.toJson<int?>(fairwayHit),
      'gir': serializer.toJson<int>(gir),
      'putts': serializer.toJson<int>(putts),
      'upDownAttempt': serializer.toJson<int>(upDownAttempt),
      'upDownSuccess': serializer.toJson<int>(upDownSuccess),
      'penaltyStrokes': serializer.toJson<int>(penaltyStrokes),
      'bunkerVisited': serializer.toJson<int>(bunkerVisited),
      'sandSave': serializer.toJson<int>(sandSave),
      'driveDistanceYards': serializer.toJson<int>(driveDistanceYards),
      'approachDistanceYards': serializer.toJson<int?>(approachDistanceYards),
      'teeClub': serializer.toJson<String?>(teeClub),
      'notes': serializer.toJson<String?>(notes),
    };
  }

  HoleResultsData copyWith({
    int? id,
    int? roundId,
    int? holeNumber,
    int? par,
    int? score,
    int? yards,
    Value<int?> fairwayHit = const Value.absent(),
    int? gir,
    int? putts,
    int? upDownAttempt,
    int? upDownSuccess,
    int? penaltyStrokes,
    int? bunkerVisited,
    int? sandSave,
    int? driveDistanceYards,
    Value<int?> approachDistanceYards = const Value.absent(),
    Value<String?> teeClub = const Value.absent(),
    Value<String?> notes = const Value.absent(),
  }) => HoleResultsData(
    id: id ?? this.id,
    roundId: roundId ?? this.roundId,
    holeNumber: holeNumber ?? this.holeNumber,
    par: par ?? this.par,
    score: score ?? this.score,
    yards: yards ?? this.yards,
    fairwayHit: fairwayHit.present ? fairwayHit.value : this.fairwayHit,
    gir: gir ?? this.gir,
    putts: putts ?? this.putts,
    upDownAttempt: upDownAttempt ?? this.upDownAttempt,
    upDownSuccess: upDownSuccess ?? this.upDownSuccess,
    penaltyStrokes: penaltyStrokes ?? this.penaltyStrokes,
    bunkerVisited: bunkerVisited ?? this.bunkerVisited,
    sandSave: sandSave ?? this.sandSave,
    driveDistanceYards: driveDistanceYards ?? this.driveDistanceYards,
    approachDistanceYards: approachDistanceYards.present
        ? approachDistanceYards.value
        : this.approachDistanceYards,
    teeClub: teeClub.present ? teeClub.value : this.teeClub,
    notes: notes.present ? notes.value : this.notes,
  );
  HoleResultsData copyWithCompanion(HoleResultsCompanion data) {
    return HoleResultsData(
      id: data.id.present ? data.id.value : this.id,
      roundId: data.roundId.present ? data.roundId.value : this.roundId,
      holeNumber: data.holeNumber.present
          ? data.holeNumber.value
          : this.holeNumber,
      par: data.par.present ? data.par.value : this.par,
      score: data.score.present ? data.score.value : this.score,
      yards: data.yards.present ? data.yards.value : this.yards,
      fairwayHit: data.fairwayHit.present
          ? data.fairwayHit.value
          : this.fairwayHit,
      gir: data.gir.present ? data.gir.value : this.gir,
      putts: data.putts.present ? data.putts.value : this.putts,
      upDownAttempt: data.upDownAttempt.present
          ? data.upDownAttempt.value
          : this.upDownAttempt,
      upDownSuccess: data.upDownSuccess.present
          ? data.upDownSuccess.value
          : this.upDownSuccess,
      penaltyStrokes: data.penaltyStrokes.present
          ? data.penaltyStrokes.value
          : this.penaltyStrokes,
      bunkerVisited: data.bunkerVisited.present
          ? data.bunkerVisited.value
          : this.bunkerVisited,
      sandSave: data.sandSave.present ? data.sandSave.value : this.sandSave,
      driveDistanceYards: data.driveDistanceYards.present
          ? data.driveDistanceYards.value
          : this.driveDistanceYards,
      approachDistanceYards: data.approachDistanceYards.present
          ? data.approachDistanceYards.value
          : this.approachDistanceYards,
      teeClub: data.teeClub.present ? data.teeClub.value : this.teeClub,
      notes: data.notes.present ? data.notes.value : this.notes,
    );
  }

  @override
  String toString() {
    return (StringBuffer('HoleResultsData(')
          ..write('id: $id, ')
          ..write('roundId: $roundId, ')
          ..write('holeNumber: $holeNumber, ')
          ..write('par: $par, ')
          ..write('score: $score, ')
          ..write('yards: $yards, ')
          ..write('fairwayHit: $fairwayHit, ')
          ..write('gir: $gir, ')
          ..write('putts: $putts, ')
          ..write('upDownAttempt: $upDownAttempt, ')
          ..write('upDownSuccess: $upDownSuccess, ')
          ..write('penaltyStrokes: $penaltyStrokes, ')
          ..write('bunkerVisited: $bunkerVisited, ')
          ..write('sandSave: $sandSave, ')
          ..write('driveDistanceYards: $driveDistanceYards, ')
          ..write('approachDistanceYards: $approachDistanceYards, ')
          ..write('teeClub: $teeClub, ')
          ..write('notes: $notes')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    roundId,
    holeNumber,
    par,
    score,
    yards,
    fairwayHit,
    gir,
    putts,
    upDownAttempt,
    upDownSuccess,
    penaltyStrokes,
    bunkerVisited,
    sandSave,
    driveDistanceYards,
    approachDistanceYards,
    teeClub,
    notes,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is HoleResultsData &&
          other.id == this.id &&
          other.roundId == this.roundId &&
          other.holeNumber == this.holeNumber &&
          other.par == this.par &&
          other.score == this.score &&
          other.yards == this.yards &&
          other.fairwayHit == this.fairwayHit &&
          other.gir == this.gir &&
          other.putts == this.putts &&
          other.upDownAttempt == this.upDownAttempt &&
          other.upDownSuccess == this.upDownSuccess &&
          other.penaltyStrokes == this.penaltyStrokes &&
          other.bunkerVisited == this.bunkerVisited &&
          other.sandSave == this.sandSave &&
          other.driveDistanceYards == this.driveDistanceYards &&
          other.approachDistanceYards == this.approachDistanceYards &&
          other.teeClub == this.teeClub &&
          other.notes == this.notes);
}

class HoleResultsCompanion extends UpdateCompanion<HoleResultsData> {
  final Value<int> id;
  final Value<int> roundId;
  final Value<int> holeNumber;
  final Value<int> par;
  final Value<int> score;
  final Value<int> yards;
  final Value<int?> fairwayHit;
  final Value<int> gir;
  final Value<int> putts;
  final Value<int> upDownAttempt;
  final Value<int> upDownSuccess;
  final Value<int> penaltyStrokes;
  final Value<int> bunkerVisited;
  final Value<int> sandSave;
  final Value<int> driveDistanceYards;
  final Value<int?> approachDistanceYards;
  final Value<String?> teeClub;
  final Value<String?> notes;
  const HoleResultsCompanion({
    this.id = const Value.absent(),
    this.roundId = const Value.absent(),
    this.holeNumber = const Value.absent(),
    this.par = const Value.absent(),
    this.score = const Value.absent(),
    this.yards = const Value.absent(),
    this.fairwayHit = const Value.absent(),
    this.gir = const Value.absent(),
    this.putts = const Value.absent(),
    this.upDownAttempt = const Value.absent(),
    this.upDownSuccess = const Value.absent(),
    this.penaltyStrokes = const Value.absent(),
    this.bunkerVisited = const Value.absent(),
    this.sandSave = const Value.absent(),
    this.driveDistanceYards = const Value.absent(),
    this.approachDistanceYards = const Value.absent(),
    this.teeClub = const Value.absent(),
    this.notes = const Value.absent(),
  });
  HoleResultsCompanion.insert({
    this.id = const Value.absent(),
    required int roundId,
    required int holeNumber,
    required int par,
    required int score,
    required int yards,
    this.fairwayHit = const Value.absent(),
    required int gir,
    required int putts,
    required int upDownAttempt,
    required int upDownSuccess,
    required int penaltyStrokes,
    required int bunkerVisited,
    required int sandSave,
    required int driveDistanceYards,
    this.approachDistanceYards = const Value.absent(),
    this.teeClub = const Value.absent(),
    this.notes = const Value.absent(),
  }) : roundId = Value(roundId),
       holeNumber = Value(holeNumber),
       par = Value(par),
       score = Value(score),
       yards = Value(yards),
       gir = Value(gir),
       putts = Value(putts),
       upDownAttempt = Value(upDownAttempt),
       upDownSuccess = Value(upDownSuccess),
       penaltyStrokes = Value(penaltyStrokes),
       bunkerVisited = Value(bunkerVisited),
       sandSave = Value(sandSave),
       driveDistanceYards = Value(driveDistanceYards);
  static Insertable<HoleResultsData> custom({
    Expression<int>? id,
    Expression<int>? roundId,
    Expression<int>? holeNumber,
    Expression<int>? par,
    Expression<int>? score,
    Expression<int>? yards,
    Expression<int>? fairwayHit,
    Expression<int>? gir,
    Expression<int>? putts,
    Expression<int>? upDownAttempt,
    Expression<int>? upDownSuccess,
    Expression<int>? penaltyStrokes,
    Expression<int>? bunkerVisited,
    Expression<int>? sandSave,
    Expression<int>? driveDistanceYards,
    Expression<int>? approachDistanceYards,
    Expression<String>? teeClub,
    Expression<String>? notes,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (roundId != null) 'round_id': roundId,
      if (holeNumber != null) 'hole_number': holeNumber,
      if (par != null) 'par': par,
      if (score != null) 'score': score,
      if (yards != null) 'yards': yards,
      if (fairwayHit != null) 'fairway_hit': fairwayHit,
      if (gir != null) 'gir': gir,
      if (putts != null) 'putts': putts,
      if (upDownAttempt != null) 'up_down_attempt': upDownAttempt,
      if (upDownSuccess != null) 'up_down_success': upDownSuccess,
      if (penaltyStrokes != null) 'penalty_strokes': penaltyStrokes,
      if (bunkerVisited != null) 'bunker_visited': bunkerVisited,
      if (sandSave != null) 'sand_save': sandSave,
      if (driveDistanceYards != null)
        'drive_distance_yards': driveDistanceYards,
      if (approachDistanceYards != null)
        'approach_distance_yards': approachDistanceYards,
      if (teeClub != null) 'tee_club': teeClub,
      if (notes != null) 'notes': notes,
    });
  }

  HoleResultsCompanion copyWith({
    Value<int>? id,
    Value<int>? roundId,
    Value<int>? holeNumber,
    Value<int>? par,
    Value<int>? score,
    Value<int>? yards,
    Value<int?>? fairwayHit,
    Value<int>? gir,
    Value<int>? putts,
    Value<int>? upDownAttempt,
    Value<int>? upDownSuccess,
    Value<int>? penaltyStrokes,
    Value<int>? bunkerVisited,
    Value<int>? sandSave,
    Value<int>? driveDistanceYards,
    Value<int?>? approachDistanceYards,
    Value<String?>? teeClub,
    Value<String?>? notes,
  }) {
    return HoleResultsCompanion(
      id: id ?? this.id,
      roundId: roundId ?? this.roundId,
      holeNumber: holeNumber ?? this.holeNumber,
      par: par ?? this.par,
      score: score ?? this.score,
      yards: yards ?? this.yards,
      fairwayHit: fairwayHit ?? this.fairwayHit,
      gir: gir ?? this.gir,
      putts: putts ?? this.putts,
      upDownAttempt: upDownAttempt ?? this.upDownAttempt,
      upDownSuccess: upDownSuccess ?? this.upDownSuccess,
      penaltyStrokes: penaltyStrokes ?? this.penaltyStrokes,
      bunkerVisited: bunkerVisited ?? this.bunkerVisited,
      sandSave: sandSave ?? this.sandSave,
      driveDistanceYards: driveDistanceYards ?? this.driveDistanceYards,
      approachDistanceYards:
          approachDistanceYards ?? this.approachDistanceYards,
      teeClub: teeClub ?? this.teeClub,
      notes: notes ?? this.notes,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (roundId.present) {
      map['round_id'] = Variable<int>(roundId.value);
    }
    if (holeNumber.present) {
      map['hole_number'] = Variable<int>(holeNumber.value);
    }
    if (par.present) {
      map['par'] = Variable<int>(par.value);
    }
    if (score.present) {
      map['score'] = Variable<int>(score.value);
    }
    if (yards.present) {
      map['yards'] = Variable<int>(yards.value);
    }
    if (fairwayHit.present) {
      map['fairway_hit'] = Variable<int>(fairwayHit.value);
    }
    if (gir.present) {
      map['gir'] = Variable<int>(gir.value);
    }
    if (putts.present) {
      map['putts'] = Variable<int>(putts.value);
    }
    if (upDownAttempt.present) {
      map['up_down_attempt'] = Variable<int>(upDownAttempt.value);
    }
    if (upDownSuccess.present) {
      map['up_down_success'] = Variable<int>(upDownSuccess.value);
    }
    if (penaltyStrokes.present) {
      map['penalty_strokes'] = Variable<int>(penaltyStrokes.value);
    }
    if (bunkerVisited.present) {
      map['bunker_visited'] = Variable<int>(bunkerVisited.value);
    }
    if (sandSave.present) {
      map['sand_save'] = Variable<int>(sandSave.value);
    }
    if (driveDistanceYards.present) {
      map['drive_distance_yards'] = Variable<int>(driveDistanceYards.value);
    }
    if (approachDistanceYards.present) {
      map['approach_distance_yards'] = Variable<int>(
        approachDistanceYards.value,
      );
    }
    if (teeClub.present) {
      map['tee_club'] = Variable<String>(teeClub.value);
    }
    if (notes.present) {
      map['notes'] = Variable<String>(notes.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('HoleResultsCompanion(')
          ..write('id: $id, ')
          ..write('roundId: $roundId, ')
          ..write('holeNumber: $holeNumber, ')
          ..write('par: $par, ')
          ..write('score: $score, ')
          ..write('yards: $yards, ')
          ..write('fairwayHit: $fairwayHit, ')
          ..write('gir: $gir, ')
          ..write('putts: $putts, ')
          ..write('upDownAttempt: $upDownAttempt, ')
          ..write('upDownSuccess: $upDownSuccess, ')
          ..write('penaltyStrokes: $penaltyStrokes, ')
          ..write('bunkerVisited: $bunkerVisited, ')
          ..write('sandSave: $sandSave, ')
          ..write('driveDistanceYards: $driveDistanceYards, ')
          ..write('approachDistanceYards: $approachDistanceYards, ')
          ..write('teeClub: $teeClub, ')
          ..write('notes: $notes')
          ..write(')'))
        .toString();
  }
}

class DatabaseAtV5 extends GeneratedDatabase {
  DatabaseAtV5(QueryExecutor e) : super(e);
  late final Courses courses = Courses(this);
  late final Events events = Events(this);
  late final Rounds rounds = Rounds(this);
  late final HoleResults holeResults = HoleResults(this);
  late final Index idxRoundsDate = Index(
    'idx_rounds_date',
    'CREATE INDEX idx_rounds_date ON rounds (date)',
  );
  late final Index idxRoundsCourse = Index(
    'idx_rounds_course',
    'CREATE INDEX idx_rounds_course ON rounds (course_id)',
  );
  late final Index idxRoundsEvent = Index(
    'idx_rounds_event',
    'CREATE INDEX idx_rounds_event ON rounds (event_id)',
  );
  late final Index idxHolesRound = Index(
    'idx_holes_round',
    'CREATE INDEX idx_holes_round ON hole_results (round_id)',
  );
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    courses,
    events,
    rounds,
    holeResults,
    idxRoundsDate,
    idxRoundsCourse,
    idxRoundsEvent,
    idxHolesRound,
  ];
  @override
  StreamQueryUpdateRules get streamUpdateRules => const StreamQueryUpdateRules([
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'events',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('rounds', kind: UpdateKind.update)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'rounds',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('hole_results', kind: UpdateKind.delete)],
    ),
  ]);
  @override
  int get schemaVersion => 5;
}
