// Guards the "drift, drift_dev and drift_flutter move together" rule (#114).
//
// The rule is stated in `.github/dependabot.yml` and `app/README.md`: the
// committed `*.g.dart` files are generated by that set, so a split bump builds
// against codegen from a different drift version. Until now the rule lived only
// in prose and in a Dependabot group, and it was already broken once — the
// drift bump in #111 moved `drift` to ^2.35.0 and `drift_flutter` to ^0.3.1 but
// left `drift_dev` declared at ^2.33.0. Nothing failed, because the caret still
// admitted 2.35.0 and that is what the lock resolved, so it went unnoticed
// until the SDK upgrade in #114 read the file.
//
// These checks are deliberately cheap: no git, no network and no sqlite, so
// this file runs on Windows without tripping the locked-sqlite3.dll crash a
// full `flutter test` can hit:
//
//   flutter test test/tool/drift_trio_test.dart

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

void main() {
  group('the drift trio moves together', () {
    late String pubspec;
    late String lock;

    setUpAll(() {
      final root = findRepoRoot();
      pubspec = File('${root.path}/app/pubspec.yaml').readAsStringSync();
      lock = File('${root.path}/app/pubspec.lock').readAsStringSync();
    });

    test('drift and drift_dev resolve to the same version', () {
      // The actual safety property. drift_dev generates the code that drift
      // runs, so a mismatch here means the committed `*.g.dart` files were
      // produced by a different drift than the one being linked against.
      final drift = lockedVersion(lock, 'drift');
      final driftDev = lockedVersion(lock, 'drift_dev');

      expect(
        driftDev,
        drift,
        reason: 'pubspec.lock has drift $drift but drift_dev $driftDev — the '
            'committed *.g.dart files would be generated by a different drift '
            'than the app builds against. Bump them together and re-run '
            '`dart run build_runner build`.',
      );
    });

    test('drift and drift_dev are declared with the same constraint', () {
      // What actually went wrong in #111. The constraints can agree with the
      // lock individually and still disagree with each other, which is how a
      // split bump hides: the caret covers for it until drift crosses the next
      // minor, and then the two can resolve apart.
      final drift = declaredConstraint(pubspec, 'drift');
      final driftDev = declaredConstraint(pubspec, 'drift_dev');

      expect(
        driftDev,
        drift,
        reason: 'app/pubspec.yaml declares drift $drift but drift_dev '
            '$driftDev. They share a version line, so the declared constraints '
            'should too — see the drift group in .github/dependabot.yml.',
      );
    });

    test('all three are present and locked', () {
      // Catches a trio member being dropped from the pubspec or the lock
      // outright, which neither check above would notice.
      for (final name in ['drift', 'drift_dev', 'drift_flutter']) {
        expect(
          declaredConstraint(pubspec, name),
          isNotNull,
          reason: '$name is not declared in app/pubspec.yaml',
        );
        expect(
          lockedVersion(lock, name),
          isNotNull,
          reason: '$name is not in app/pubspec.lock',
        );
      }
    });
  });
}

/// The version `pubspec.lock` resolved for [name], or null if it is absent.
///
/// Entries look like:
///
///     drift_dev:
///       dependency: "direct dev"
///       description:
///         ...
///       source: hosted
///       version: "2.35.0"
String? lockedVersion(String lock, String name) {
  final lines = lock.split('\n');
  final header = RegExp('^  $name:\\s*\$');
  final version = RegExp(r'^\s+version:\s*"?([^"\s]+)"?\s*$');

  for (var i = 0; i < lines.length; i++) {
    if (!header.hasMatch(lines[i])) continue;
    // Scan the entry's body; a new top-level entry ends it.
    for (var j = i + 1; j < lines.length; j++) {
      if (RegExp(r'^  \S').hasMatch(lines[j])) break;
      final m = version.firstMatch(lines[j]);
      if (m != null) return m.group(1);
    }
  }
  return null;
}

/// The constraint [name] is declared with in `pubspec.yaml`, or null if it is
/// not declared. Matches in either `dependencies:` or `dev_dependencies:`,
/// which is the point — `drift` sits in one and `drift_dev` in the other.
String? declaredConstraint(String pubspec, String name) {
  final entry = RegExp('^  $name:\\s*(\\S+)\\s*\$', multiLine: true);
  return entry.firstMatch(pubspec)?.group(1);
}

/// Walks up from the test's working directory (`app/` under `flutter test`)
/// until the repo root — the directory holding CHANGELOG.md — is found.
Directory findRepoRoot() {
  var dir = Directory.current;
  for (var i = 0; i < 4; i++) {
    if (File('${dir.path}/CHANGELOG.md').existsSync()) return dir;
    dir = dir.parent;
  }
  throw StateError('could not find the repo root above ${Directory.current}');
}
